### ISSUE TITLE
Automatické testy

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#1170]
- [x] Nasadit řešení na .24 a předat všem vývojářům.
- [x] Odstranit nepoužívané unit testy (https://github.com/ARUP-CAS/aiscr-webamcr/actions/workflows/ci.yml) a související kód.

**Comment by pesikj** [comment]
@motyc Jak už jsme spolu probírali, tyto automatické testy již nejsou použitelné, protože z GitHubu nemáme připojení do repozitáře Fedory. Testy jsem tedy odstranil.

**Comment by motyc** [comment]
@pesikj Rozumím. Jen jsem koukal, že jste odstranil pouze danou workflow. Bylo by myslím dobré dát pryč i související kód, protože stejně zastaral a jen nám bude zatěžovat repozitář (např. i při hledání výskytů různých funkcí atd.). Pokud tedy není nějaký dobrý důvod, proč kód testů zachovat.

**Comment by pesikj** [comment]
@motyc Podle mě by bylo dobré to ještě projít a podívat se, které situace máme naprogramované, aby to případně mohlo být přepsáno do Seleinum testů.

**Comment by motyc** [comment]
Základ ok, nechávám otevřené kvůli tomu vytěžení existujících testů.

**Comment by motyc** [comment]
@jhavrlant Aktualizoval jsem první komentář tak, aby shrnoval úkoly, které je třeba dodělat. Zároveň zde odpovídám na dva reportované problémy:

> testovací scénář 2.3 Zapsání projektu (negativní scénář 1) – projde uložení https://aiscr-webamcr.readthedocs.io/cs/latest/automaticke_testy.html#zapsani-projektu-negativni-scenar-1

Podle mně ten scénář nikdy nemohl fungovat, protože žádné pravidlo pro zápis plánovaného zahájení v tomto smyslu není. Nenapadá @pesikj, z čeho jste vycházel?

> negativnu testovací scénář `Scenar_39` nefunguje – uloží se https://docs.google.com/document/d/1qJArruTG-iUNKQkuxtgB2Bz4zzfZYVCKtMhJBKyYP8E/edit#heading=h.xdbhlgqp4ewa

Chyba. Založeno issue #1754

**Comment by motyc** [comment]
- [ ] `pas.tests.test_selenium.AkceSamostatneNalezy.test_039_archivace_samostatneho_nalezu_n_001` - #1754
- [ ] `lokalita.tests.test_selenium.AkceLokality.test_058_archivace_lokality_p_001` - #1535 
- [ ] `lokalita.tests.test_selenium.AkceLokality.test_060_vraceni_odeslane_lokality_p_001` - #1535 (doplněno jako nová chyba)
- [ ] `dokument.tests.test_selenium.AkceDokumenty.test_066_odeslani_dokumentu_p_001` - @jhavrlant toto neumím nasimulovat, resp. potřebuji více informací - o jaký dokument se jedná? Není problém v oprávnění, když se nejde přes "Moje dokumenty"? Co systém vrátí za hlášku? Je tam korektně nahraný soubor (u starých dokumentů nejsou).

**Comment by jhavrlant** [comment]
> * dokument.tests.test_selenium.AkceDokumenty.test_066_odeslani_dokumentu_p_001

@motyc chyba bude v testu. Musím se na něj podívat.
