### ISSUE TITLE
Testování - zbývající chyby (vytříděno ze zavíraných issue)

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#240]
- [x] - přidání ADB vrací error 500 (viz https://github.com/ARUP-CAS/aiscr-webamcr/issues/192#issuecomment-919253246 a další komenty)
- [x] - https://github.com/ARUP-CAS/aiscr-webamcr/issues/132 - ve formuláři i tabulce chybí pole: Jméno, Příjmení a Telefon
- [x] - https://github.com/ARUP-CAS/aiscr-webamcr/issues/102 - U komponenty stále chybí checkbox “Nejistá datace”
- [x] - https://github.com/ARUP-CAS/aiscr-webamcr/issues/102 - Logika přidávání DJ je stále chybná (musí platit ve všech případech přidávání i editace):
-- u první DJ má být pouze volba “Celek akce” nebo “Sonda” (jiné volby u projektových akcí nepřichází v úvahu)
-- u každé další DJ na základě první pouze “Část akce” nebo “Sonda”
-- pokud změním první DJ z “Celek akce” na “Sonda”, musí se automaticky upravit i ostatní existující DJ (“Část” -> “Sonda”) a naopak
- [x] - https://github.com/ARUP-CAS/aiscr-webamcr/issues/102 - Pokud nevyplním specifikaci u předmětu, hlásí pouze “Záznam se nepovedlo editovat” - je třeba být přesnější, uživateli vůbec nedojde, proč to nejde uložit.
- [x] - https://github.com/ARUP-CAS/aiscr-webamcr/issues/102 - Tlačítko "Upravit předměty" je stále bez diakritiky.

**Comment by pbartosova** [comment]
K bodu: 
-- pokud změním první DJ z “Celek akce” na “Sonda”, musí se automaticky upravit i ostatní existující DJ (“Část” -> “Sonda”) a naopak
Proč řešíme změnu DJ, když ve stávající aplikaci toto není možné ani při stisknutí tlačítka "Zahájit Editaci" , které přebije všechnu logiku a vesměs povolí vše.

**Comment by jnihnat** [comment]
bod 5 opraven v #242 - po merge a nasazeni mozne otestovat

**Comment by pbartosova** [comment]
Všechny tasky hotové.

**Comment by motyc** [comment]
Otestováno, jediná drobnost ad 2 - Jméno a příjmení (telefon asi můžeme vynechat) je třeba vypsat i v tabulce, nejen v detailu uživatele.
