### ISSUE TITLE
Modul Dokumenty - dokončení

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#320]
Přidávání dokumentů je již částečně implementováno jako součást workflow projektových akcí. Jedná se o základ, resp. specifické užití, které je třeba dále rozvinout a doplnit o celkovou správu dokumentů.

Celkové řešení formulářů viz: https://docs.google.com/spreadsheets/d/1LzGctLXR5-9MJl1rG75l6rKrJ7BvzXDGdSQ_uloyuSg/edit#gid=931266329

Co je třeba dodělat:
- [x] Samostatnou položku “Dokumenty” na úvodní obrazovce (modrá barva - #5882c4) a související menu, s volbami:
- Zapsat dokument (obdoba http://192.168.254.30:8080/dokument/zapsat/ bez vazby na projekt)
- Vybrat dokumenty
- Moje dokumenty
- Archivovat dokumenty
- Spravovat lety (samostatné issue #321)
- [x] Doplnit view http://192.168.254.30:8080/dokument/detail/ v sekci Části dokumentu o:
- Možnost vytvářet nové části, připojovat je na archeologické záznamy a projekty typu průzkum, odpojovat je či odstraňovat
- Práci s komponentami a nálezy dokumentu (zobrazení, přidávání, editace, odebírání - ekvivalent téhož u archeologických záznamů)
- Práci s neidentifikovanými akcemi (zobrazení, editace a odebírání; obdoba řešení pro ADB u akcí)
- [x] U Letu umožnit proklik na detail (samostatné issue #321)
- [x] Přidat tabulku výpisem navázaných tvarů (tabulka “Tvary”)
- řešit podobně jako nálezy u komponenty
- možnost přidávání, editace a odebírání
- [x] Kromě tabulkového zobrazení vybraných dokumentů umožnit zobrazení:
- galerie s náhledy
- náhledů souborů v detailu dokumentu
- [x] Tabulku soubory posunout nad detail
- [x] Rozšířit akceptované formáty souborů na: PDF, TXT, CSV, TIFF (TIF), JPEG (JPG), PNG
- [x] Vyřešit problém s přidáváním více autorů (v daném pořadí) (původně #64)

**Comment by motyc** [comment]
Vzorové řešení pro autory podle Academi.edu:
![image](https://user-images.githubusercontent.com/20186892/151406417-a0105f76-fed3-4fd0-904d-21c76a51cc2f.png)

**Comment by jnihnat** [comment]
@motyc - Prosim tu taky jako u ostatnich tabulek dodat ktere sloupce se maji zobrazovat a ktere z nich se maji primarne scovavat ve vyberu. Dekuji.

**Comment by jnihnat** [comment]
@motyc - prosim jeste dalsi dotazy:
- Neident akce znamena ze Dokument nema zadnu vazbu na Akci? nebo na akci a projekt? Nebo neco jineho?
- ve filtraci radek 4 s ano/ne moznostami, znamena ze dokument ma aspon jednu vazbu na dany model nebo nema zadnu?
Dekuji

**Comment by motyc** [comment]
@jnihnat 
ad pole - tabulky (**výchozí**):
- **ident_cely**
- **stav**
- **organizace**
- **autor** (agregováno podle dokument_autor)
- **rok_vzniku**
- **typ_dokumentu**
- **popis**
- **pristupnost**
- rada
- let
- material_originalu
- poznamka
- ulozeni_originalu
- oznaceni_originalu
- datum_zverejneni
- licence

ad neident. akce - jde o samostatnou strukturu napojenou 1:1 vůči části dokumentu (viz v DB tabulka neident_akce a související)

ad ano/ne - přesně tak

**Comment by jnihnat** [comment]
@motyc - prosim dalsi doplnujici dotazy:
- let - stav - ten nikde nevidim, ani v databazy, je to chyba v zadani?
- tvary - mate tam vicestupnovy heslar. nikde ale vazbu nadrazene/podrazene nevidim, je to chyba nebo chybi heslar?
- soubor - typ - o jaky typ se jedna? v db je typ_souboru, ale to nema vazbu na zadneho heslare a ani se pri ukladani nedoplnuje. Pak mame jeste mimetype, ale na to taky neni heslar.
- id letu - je 2x v sekci lety a v sekci vazby. Chceme to tak?
- sloupec autori - nebude mozne podle neho radit ptoroze se jedna o Many to Many relaci.

**Comment by motyc** [comment]
@jnihnat Pardony za chyby v zadání, asi jsem to dělal nějaký unavený:
- let - stav - vynechat, bylo to přeneseno z #321, kde jsou plánované úpravy; dělat se to ale určitě v dohledné době nebude;
- účel letu - to je také chyba, nemá být samostatné pole a je to zahrnuté mezi popisnými údaji
- tvary - opět překlep
(opravil jsem patřičně danou sekci zadání formuláře)
- soubor - typ - navazuje na pole soubor.mimetype; jde sice o textové pole, ale mělo by obsahem odpovídat standardu "mimetype" (https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types); zde jsem to myslel tak, že by to nabízelo existující varianty z DB, pokud to není problém
- id letu - ano, to nedává smysl - nechávám pouze v sekci letů
- autori - to je trošku nepříjemné, nejde to agregovat jako textový řetězec, který by řadit šel, nebo alespoň podle prvního autora? Pokud je to problém, můžeme si k tomu nějak zavolat a dohodnout se.
- zápis - máte pravdu, zapomněl jsem na to; udělal bych to tak, že při zápisu přímo z menu vyskočí modal s dotazem, zda je územní příslušnost dokumentu "Čechy", nebo "Morava a Slezsko" (znění doladím); podle volby by se pak stanovoval ident_cely a vše může běžet standardně
- pouze pro letecké snímky znamená, že řada dokumentu je LD, LN nebo DL

**Comment by motyc** [comment]
@jnihnat
Ad náhledy v detailu dokumentu - 1) pro zjednodušení asi opravdu zatím pracujme jen s obrázkovými dokumenty, s PDF a jinými typy by to bylo složitější a ani to nemá moc význam; 2) nebylo by možné pro ty obrazové dokumenty zobrazit malý náhled (řekněme 100 px vysoký) a na kliknutí v modal větší?

Jak to uděláme s tou galerií ve výsledcích výběru (filtrace)? Máte nějaký návrh? Tam by bylo dobré také malé náhledy vidět rovnou, nikoli až na kliknutí (mají sloužit k lepší orientaci např. ve fotkách).

**Comment by jnihnat** [comment]
co se tyce vyberu, muzeme udelat neco takoveto:
![image](https://user-images.githubusercontent.com/57906106/203757390-309b97d8-c341-410d-b045-754e296e3873.png)
rozbalovalo by se to na klik na cely radek, nebo na ikonu oka (ta tam taky nemusi byt)
taky muzou byt pri nacitani stranky vsetky rozbalene. 
Pridal by som i nekde tlacitko na rozbalit vsechny/zabalit vsechny
a jeste tu galeriu by som udelal posuvnou sipkami na okrajoch, pokud by bylo obrazku hodne u dokumentu.
@motyc prosim o vase pripominky. Dekuji

**Comment by jnihnat** [comment]
jen doplnim ze to je jen rychlo udelany navrh, jeste by se to doladilo podle vasich pripominek samozrejme.

**Comment by motyc** [comment]
@jnihnat
V 99% je u dokumentu je jeden soubor, zvláště u obrazových dokumentů. Navrhoval bych to tedy zachovat jako tabulku a jen doplnit sloupec s náhledem prvního souboru, který by šel zobrazit/skrýt (celý ten sloupec). Tím by se to myslím hodně zjednodušilo... Další soubory by byly vidět až v detailu dokumentu, kde je to už co řádek, to soubor (takže v podstatě totéž na jiné úrovni). Co myslíte?

**Comment by jnihnat** [comment]
Za mne Vami navrhovane reseni je nejjednoduchsi. Pridam teda na konec listu skryty sloupec s prvnim obrazkovym souborem. Dekuji

**Comment by motyc** [comment]
### Výsledek testu
- [ ] http://192.168.254.30:8080/dokument/vyber + http://192.168.254.30:8080/historie/soubor/50019 - šedá barva místo modré (pozor, ať se změnou neupraví i http://192.168.254.30:8080/dokument/model/vyber (atd.)
- [ ] http://192.168.254.30:8080/dokument/zapsat - error 500 při pokusu o zápis
- [ ] pokud zapisuji dokument přes http://192.168.254.30:8080/dokument/zapsat/do-akce/, neměl by se zobrazovat modal s výběrem regionu (jde dovodit z nadřazeného záznamu)
- [ ] http://192.168.254.30:8080/dokument/detail/ - v detailu nejsou vidět autoři + nezobrazuje se obsah pole Typ dokumentu pro DL, DT, DY, LD, PY, FT, DP; u DD a TX se zobrazuje
- [ ] http://192.168.254.30:8080/dokument/detail/C-DD-201800001 - dokument se nearchivuje, i když vše zdánlivě proběhne, po potvrzení v modalu zůstane ve stavu “odeslaný”
- [ ] v menu a na domovské stránce modulu chybí položka “Archivovat dokumenty”
- [ ] nejde archivovat dokumenty (D2 -> D3)
- [ ] http://192.168.254.30:8080/nahrat-soubor/dokument/ - při výběru souboru k nahrání je nějaký divný filtr podle typu souboru, který skrývá např. PDF - nevím; jak je to nastaveno moc nechápu, ale je to chybně. Správné nastavení má být na formáty: PDF, TXT, CSV, TIFF (TIF), JPEG (JPG), PNG
- [ ] U komponent nefunguje automatické předvyplnění aktivit podle areálu
- [ ] U předmětů nefunguje automatické předvyplnění specifikace podle druhu
- [ ] Nálezy u komponenty nelze odstraňovat (nic nedělá)
- [ ] Připojit volby připojit akci/lokalitu/projekt by měly být dostupné jen tehdy, pokud ještě nic připojené není; volba odpojit naopak jen tehdy, pokud něco připojené je.
- [ ] http://192.168.254.30:8080/dokument/detail/C-TX-199002099/cast/C-TX-199002099-D001 - error 500 (pokud byl dokument ve stavu D3 šla neident akce normálně otevřít; po posunu do D2 to vrací chybu)
- [ ] Pokud není část dokumentu na nic napojená, nezobrazovat prázdnou závorku
- [ ] Ikonu pro neident akci dát na konec řádku (bude to myslím vypadat lépe) a vyměnit za https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Abrush%3AFILL%401%3Bwght%40400%3BGRAD%400%3Bopsz%4048
- [ ] http://192.168.254.30:8080/dokument/zapsat + http://192.168.254.30:8080/dokument/edit/ - chybí tlačítko pro přidání nové osoby u pole Autoři a Dokumentované osoby (máme případně i v #670)
- [ ] http://192.168.254.30:8080/nahrat-soubor/dokument/C-DL-200000001 - pokud nahraji duplicitní soubor, opět se oběvuje nesmyslná hláška a nahrát nejde
- [ ] při posunu akce z A1 do A2 nedojde k posunu napojených dokumentů z D1 do D2 (dříve fungovalo)

**Filtrace** (http://192.168.254.30:8080/dokument/vyber a odvozené obrazovky)
- [ ] náhled by bylo dobré mít možnost rozkliknout, jako je to v detailu
- [ ] sloupec s náhledem dávat na první místo (ve výběru i v detailu) a dát jeho zobrazení jako zapnuté ve výchozím režimu
- [ ] http://192.168.254.30:8080/dokument/vyber?sort=pristupnost - řadí se správně pouze někdy (nepodařilo se vysledovat jasné pravidlo)
- [ ] pokud jako první zadám řazení podle Autori, další sloupce už se seřadit nepodaří (např. http://192.168.254.30:8080/dokument/vyber?sort=organizace__nazev_zkraceny&sort=autori)
- [ ] pole Přístupnost má label “dokument.filter.ulozeniOriginalu.label”
- [ ] u většiny polí je jako oddělovač multihodnot pro výběr použitá čárka místo dříve dohodnutého středníku
- [ ] error 500 při hledání podle oddíl Historie - filtr Typ změny nebo oddíl Soubory - rozsah stran
- [ ] oddíl Extra data - v poli Formát je heslář pouze pro 3D, má být naopak vše kromě 3D
- [ ] v oddíle komponenta-nález je u předmětu položka “**lokalita**.filter.predmetPoznamkaPocet.label”; dtto pro objekt je  “**lokalita**.filter.objektPoznamkaPocet.label “
- [ ] v oddíle Lety/Tvary je popisek “dokument.filter.letId.label” dvakrát, podruhé u data letu
- [ ] v oddíle Soubory je u typu souboru popisek “dokument.filter.tvaryPoznamka.label”
- [ ] oddíl Soubory - rozsah velikosti je zapotřebí zadávat v kB, ale v detailu je v bytech - sjednotit všude na MB (pokud to není problém)
- [ ] pole Material originalu zůstává prázdné v exportovaných tabulkách

**Comment by jnihnat** [comment]
@motyc - dotazy k bodum z testovani:
- farba u historie/soubor - ta je tedka stejna pro vsechny historie souboru, nerozlisuje se podle nadrazene entity. Tedka je tam farba #6c697b Kdyz bychom to chteli menit tak prosim samostatne issue bude to totiz potreba pretestovat vsude.
- z nejakeho duvodu chybeli v DB 2 sloupce: heslar_dokument_typ_material_rada.validated a ruian_katastr.poznamka -podle vseho nema vyznam jich mit v DB, ale jsou v kodu, tak pokud se maji odstanit, musi se odstranit i v kodu. (@pesikj @pbartosova )
- typ dokumentu - pri zadavani je tedka omezeni na nektere typy (DATA_GPS, EXPERTNI_POSUDEK, HLASENI_ZAA,  TYP_DOKUMENTU_NALEZOVA_ZPRAVA, DATA_ANALYZY_EKOFAKTORU, INVESTORSKA_ZPRAVA, RESTAURATORSKA_ZPRAVA,    DATA_VEKTOROVEHO_PLANU, TEXT_JINY, DATA_TERENNIHO_VYZKUMU, PRILOHA_NZ_ZAA, DATA_GEOFYZIKALNI, DATA_GEODETICKA,) Plati tohle stale?
- pri archivaci je nastavene posilani emailu 'E-K-01' na uzivatele co zapsal dokument. v nekterych pripadech ale takovy uzivatel neexistuje. Je teda spravne ak se takovy mail neodesle?
- pripojovani/odpojovani akce/projektu/lokalit - odpojit chapu. Pripojeni je delane ze automaticky pred tim odpoji zaznam. Pokud to chcete mit jak pisete nerobi mi to problem, jen radeji se ptam ci to naozaj chceme, takto pokud chce uzivatel nahradit pripojeni je o jeden ktok mene.
- nezobrazeni detailu casti s neident akci souvisi s odmazanim ident_cely u neident_akce v ramci #474. Je tohle finalni stav a mam se tomu prispusobit? Potrebuji pak upravit vice veci a zobrazovani identu kde se zobrazoval.

**Comment by motyc** [comment]
@jnihnat 
- barva - ok
- sloupce - ano, ty byly odstraněny záměrně
- typ dokumentu - zatím ano, ale udělám pro to issue; musíme to promyslet interně
- email - ano, to je logické a nevadí to
- pripojovani/odpojovani - máte pravdu, že je to o kliknutí navíc, ale je to srozumitelnější pro uživatele, protože jinak by se mohlo snadno stát, že si nahradí vazbu, kterou vůbec nahradit nechtěl (nedojde mu, že připojením jiného záznamu dojde k odpojení původního)
- nezobrazeni detailu - ano, to by měl být finální stav (jen si prosím potvrďte s @pbartosova)
- duplicitní soubor - z boxu bohužel nejde kopírovat; jde o tento soubor: [ferda_hovor.jpg](https://user-images.githubusercontent.com/20186892/206902890-d0c51a06-2c4d-436f-af31-4a0ce5f2b50b.jpg)
![image](https://user-images.githubusercontent.com/20186892/206902875-2e1ecdfe-d922-4878-9399-c0815eaedba2.png)
- tlačítka pro osoby - ok, souhlasím

**Comment by jnihnat** [comment]
k uploadu dokumentu hore, v DB byly zaznamy souboru, ktere nebyli prirazene k dokumentu/projektu. Dane zaznamy jsem odstranil z DB. 
Ohledne zobrazovani velikosti souboru v MB. Muzeme to udelat v samostatnom issue? Je to zmena ktera se zobrazuje na vicerych mistech, tak at se to pak pretestuje vsudy. L tomu, muzeme to rovno zmenit pri ukladani do DB at se to uklada jako MB? Pripadne na kolik desatinnych mist? Zmena uz bude jednoducha, ale nech sa to otestuje vsude.

**Comment by motyc** [comment]
@jnihnat
- problémy se souborem - to ale tím pádem muselo vzniknout prací v aplikaci, protože poprvé se mi soubor podařilo nahrát, pak už to ale fungovat přestalo a myslel jsem si, že je to kvůli duplicitě
- velikost souboru - souhlas, uděláme zvlášť

**Comment by pbartosova** [comment]
Dva komentáře: 
* heslar_dokument_typ_material_rada.validated a ruian_katastr.poznamka jsou v DB smazány, v kódu by se měly vyskytovat pouze v modelu, a to by mělo vyřešit nasazení branch feature/474-revize-db (dnes). Pokud by se objevily i někde jinde, je nutné mi dát hned vědět.
* nerozumím komentáři k neident akci.ident_cely - ano toto pole by mělo být z DB smazáno, po releasu feature/474-revize-db , teď ale v db pořád je i v modelu, nemělo by tedy způsobovat žádný problém. Pokud někde v návrhu toto pole bylo uvažováno, jedná se o chybu v návrhu a změna požadavku by měla být diskutována s @sedmar .
Do vyřešení této diskuse pole zůstane i v DB:

**Comment by motyc** [comment]
@pbartosova V návrhu za naší strany se s polem nepočítá. Myslím, že se @jnihnat právě ujišťuje, co je žádoucí cílový stav. Asi by se to tedy mělo odmazat z DB i modelu, aby se to dalo správně dodělat.

**Comment by motyc** [comment]
### Výsledek testu
- [ ] "Archivovat" v menu po doplnění opět vede na http://192.168.254.30:8080/dokument/vyber?stav=3 místo http://192.168.254.30:8080/dokument/vyber?stav=2
- [ ] Archivace funguje jen pro dokumenty s trvalým ident_cely; např. pro http://192.168.254.30:8080/dokument/detail/X-C-TX-201700354 to stále nefunguje
- [ ] k dokumentu http://192.168.254.30:8080/dokument/detail/X-C-DD-202107044 jsem zkusil nahrát hromadně obsah celé složky: [Test.zip](https://github.com/ARUP-CAS/aiscr-webamcr/files/10217394/Test.zip)
-- správná přípona/typ podle výčtu v zadání se testuje chybně (PDF, TXT, CSV, TIFF (TIF), JPEG (JPG), PNG) - nahrál, se i soubor `BMP.bmp` - asi jsou nastaveny obecně obrazové soubory jako povolené, což nechceme (jen specifické formáty ve výčtu);
-- ve dvou případech se zobrazila ona nečitelná hláška (viz https://github.com/ARUP-CAS/aiscr-webamcr/issues/320#issuecomment-1345539241)
- [ ] error 500 při snaze zapsat novou komponentu (http://192.168.254.30:8080/dokument/detail/X-C-DD-202107044/cast/X-C-DD-202107044-D001/komponenta/zapsat)
- [ ] menu u části dokumentu se liší pro http://192.168.254.30:8080/dokument/detail/C-DL-200200015/cast/C-DL-200200015-D001 a pro http://192.168.254.30:8080/dokument/detail/C-DL-200200015/komponenta/C-DL-200200015-K001 - mělo by zůstat shodné (podle první varianty); ve druhém případě navíc nefunguje volba "smazatCast"
- [ ] http://192.168.254.30:8080/dokument/detail/C-TX-199002099/cast/C-TX-199002099-D001 - error 500 (pokud byl dokument ve stavu D3 šla neident akce normálně otevřít; po posunu do D2 to vrací chybu) - nadále platí
- [ ]  http://192.168.254.30:8080/dokument/vyber?sort=pristupnost - řadí se správně pouze někdy (nepodařilo se vysledovat jasné pravidlo) - stále platí:
![image](https://user-images.githubusercontent.com/20186892/207319186-4e9adb51-97c9-448a-8286-b14135550e05.png)

**Comment by jnihnat** [comment]
pro posledni bod jsem pustil migraci, uz by to mnelo fungovat, na zvysok se jeste podivam.

**Comment by motyc** [comment]
### Výsledek testu
- [ ] http://192.168.254.30:8080/dokument/ - stránka je rozbitá - patička se zobrazuje vpravo jako sloupec
- [ ] http://192.168.254.30:8080/dokument/detail/X-C-TX-201700354 - stále nejde archivovat, asi to bude nějaký speciální případ (jiné jdou)

Jinak bezva.

**Comment by jnihnat** [comment]
opraveno v #825 .
K druhymu bodu - je to spuzobeno tim, ze soubor neni v ulozisku. Osetril jsem to, ze se tedka zobrazi tedka uz spravna error chyba.
