### ISSUE TITLE
Správa automatických úloh

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#387]
### Automatické úlohy

- [x] doplnit transakce
- [x] Před nasazením je třeba promyslet situace kdy úloha ovlivní velké množství záznamů, což může vést k problémům s ukládáním změn do Fedory.

(nastavit v Celery, vč. srozumitelného popisu)
- [x] Rok po zrušení projektu nahradit související údaje v tabulce oznamovatel řetězcem “RRRR-MM-DD: údaj odstraněn”, kromě pole projekt.oznamovatel + odstranit projektovou dokumentaci a vytvořit log (jako při archivaci projektu).
- [x] Deset let po zápisu projektu smazat související záznam z tabulky oznamovatel + odstranit projektovou dokumentaci a vytvořit log (jako při archivaci projektu).
- [x] Každý den změnit přístupnost dokumentů, u kterých datum_zverejneni<=[dnes], a to na přístupnost stanovenou v hesláři organizace (podle vazby dokument.organizace), ale nikdy ne na vyšší přístupnost, než má nejlépe přístupný připojený archeologický záznam (tj. když mají připojené AZ C a D, bude mít dokument nejvýše C).
- [x] Každý den zkontrolovat a případně odeslat upozornění uživatelům na základě pole projekt.datum_odevzdani_NZ pokud je projekt ve stavu =P4 a zároveň:
-- pokud [dnes] + 90 dní = datum_odevzdani_NZ => email E-NZ-01
-- pokud [dnes] - 1 den = datum_odevzdani_NZ => email E-NZ-02
(odesílat čistě podle splnění podmínek v dané datum; neřešit log odeslaných - tj. pokud maily neodejdou, přežijeme to)
- [x] Každý den smazat projekty ve stavu -1, které vznikly před více než 12 hodinami.
-- při mazání projektů v -1 je třeba smazat i data z Fedory
- [x] Každý den převést na P8 projekty v P1 starší tří let, které mají plánované datum zahájení více než rok v minulosti. Do poznámky ke zrušení uvést “Automatické zrušení projektů starších tří let, u kterých již nelze očekávat zahájení.”
- [x] Každý den kontrola a odeslání emailů E-N-01 a E-N-02
-- viz https://docs.google.com/document/d/16ByqpA4RaB96F5YwT5no9313LRJknlbo7lwGo0YqZcM/edit
- [x] pian_to_sjtsk - doplňuje chybějící 5514 - nevolá se pravidelně, ale ponechat
- [x] https://github.com/ARUP-CAS/aiscr-webamcr/issues/1712#issuecomment-2063022941 - je potřeba přidat v administraci Task update_materialized_views pro aktualizaci heatmap.

**Odloženo**
- [ ] Jednou měsíčně (nebo přímo na základě dostupnosti změn?) stáhnout aktualizaci heslářů RÚIAN (**dohodnout podrobné zadání**; souvisí s #372)
- [ ] nastavit pravidelné kontroly fixity přes Celery, s upozorněním adminů při chybách (volba v notifikacích přes admin rozhraní) - navazuje na #365

**Comment by pesikj** [comment]
Odhad: 20 hodin

**Comment by jiri-bartos-huld** [comment]
@pesikj jedna se o tyto 2 tasky-opravil jsem a aktualizoval

@shared_task
def nalez_to_sjtsk
def pian_to_sjstk

**Comment by motyc** [comment]
### Test v1.0.0-RC2.4
- [ ] hodně jsem toho upravil v #2062 - prosím o kontrolu a merge před zapracováním dalších oprav
- [ ] `Každý den kontrola a odeslání emailů E-N-01 a E-N-02` - toto je špatně na tolika úrovních, že bych skoro doporučoval to celé napsat znovu, s tím, že:
-- funkci `send_notifications` rozdělte na dvě samostatné (`send_notifications_enz` a `send_notifications_en`), kdy jedna bude posílat E-NZ-* (ta je po mé drobné korekci již ok) a druhá E-N-* (již hotovo v #2062)
-- do emailů E-N-* se vždy agregují ident_cely sam. nálezů dotýkajících se daného adresáta (nyní se tam asi chtějí vkládat id projektů)
-- pro E-N-01 platí tento výběr:
```plpgsql
SELECT DISTINCT sn.ident_cely, u.email FROM samostatny_nalez sn
	JOIN projekt pr ON sn.projekt = pr.id
	JOIN historie h1 ON sn.historie = h1.vazba
	JOIN historie h2 ON sn.historie = h2.vazba
	JOIN uzivatel_spoluprace s ON h1.uzivatel = s.spolupracovnik
	JOIN auth_user u ON s.vedouci = u.id
	JOIN auth_user_notifikace_typ un ON u.id = un.user_id
	JOIN notifikace_typ nt ON un.usernotificationtype_id = nt.id
WHERE h1.typ_zmeny = 'SN01' AND pr.organizace = u.organizace AND nt.ident_cely = 'S-E-N-01' AND h2.typ_zmeny = 'SN12' AND h2.datum_zmeny = {yesterday};
``` 
-- pro E-N-02 platí tento výběr:
```plpgsql
SELECT DISTINCT sn.ident_cely, u.email FROM samostatny_nalez sn
	JOIN historie h1 ON sn.historie = h1.vazba
	JOIN historie h2 ON sn.historie = h2.vazba
	JOIN auth_user u ON h1.uzivatel = u.id
	JOIN auth_user_notifikace_typ un ON u.id = un.user_id
	JOIN notifikace_typ nt ON un.usernotificationtype_id = nt.id
WHERE h1.typ_zmeny = 'SN01' AND nt.ident_cely = 'S-E-N-02' AND h2.typ_zmeny = 'SN34' AND h2.datum_zmeny = {yesterday};
``` 
-- viz také https://docs.google.com/document/d/16ByqpA4RaB96F5YwT5no9313LRJknlbo7lwGo0YqZcM/edit
- [ ] `delete_personal_data_canceled_projects` v principu to funguje ok, ale z nějakého důvodu se ve Fedoře pro každý takto upravený záznam udělá nikoli jedna nová verze, ale čtyři, jak kdyby to chybně pracovalo s transakcí, nebo se to poslalo nějak vícekrát - viz např.: https://fedora-test.aiscr.cz/rest/AMCR/record/C-201017166/fcr:versions (již první upravená verze je přitom dobře). Mám takové tušení, že to mohlo být tím, že je špatně filtrace a že se každý projekt do seznamu dostává tolikrát, kolik měl záznamů v historii, tj. že tam v dotazu chybí nějaký distinct... Pokud ano, zkontrolovat i u dalších úloh.
- [ ] spuštěním `delete_personal_data_canceled_projects` se mi podařilo srazit kontejner `webamcr_web.1` - zjevně začnou v nějakém momentě selhávat healthchecky i když generování dat pokračuje - musíme to nějak ošetřit lépe - patrně by pomohlo pomoci donutit celery, aby svůj helthcheck dávalo na začátek fronty, nikoli na její konec

**Comment by pesikj** [comment]
@motyc 

>spuštěním delete_personal_data_canceled_projects se mi podařilo srazit kontejner webamcr_web.1 - zjevně začnou v nějakém momentě selhávat healthchecky i když generování dat pokračuje - musíme to nějak ošetřit lépe - patrně by pomohlo pomoci donutit celery, aby svůj helthcheck dávalo na začátek fronty, nikoli na její konec

Protože toto počáteční zpracování trvá dlouhou dobu, nemá smysl to spouštět jako naplánovanou úlohu, ale dává mnohem větší smysl spustit to přímo ze shellu.

**Comment by motyc** [comment]
@pesikj Souhlas, první spuštění uděláme takto, pak už to poběží jako naplánovaná úloha. Podobně to bude u `delete_reporter_data_ten_years`.

**Comment by motyc** [comment]
### Test Test v1.0.0-RC3.2
- [ ] kontrola a merge #2071 (není třeba kontrolovat SQL - jen jsem doplnil úpravy tak, aby po spuštění byly základní úlohy již vyřešené, pokud by jinak dat bylo příliš mnoho)
- [ ] `delete_reporter_data_ten_years` - metadata se vytvoří příliš brzy, změna se v nich neprojeví (jinak ok)
- [ ] `change_document_accessibility` - nepodařilo se mi rozjet, nic neudělalo; asi bude nějaká chyba v podmínce, ale nevidím ji
- [ ] `send_notifications_enz` - nic se nepošle; moc nevím, kde je problém (minule to šlapalo)
- [ ] `send_notifications_en` - tady se také nic nepošle, ale myslím, že vím i důvod - ptáme se na `historie__historie__datum_zmeny=timezone.now().date() + timedelta(days=-1)`, jenže `historie__historie__datum_zmeny` je timestamp - muselo by se to tedy trefit na naprosto přesný čas. Je tedy třeba upravit podmínku buď tak, aby historie__historie__datum_zmeny bylo ořezáno na dtum, nebo se to ptalo nějak takto =`datum_zmeny > (CURRENT_DATE - INTERVAL '2 day') AND datum_zmeny < (CURRENT_DATE)`
- [ ] `delete_unsubmited_projects` - tohle bohužel též nefunguje, ale problém je v datech - záznam v historii se vytvoří nikoli při zápisu projektu do stavu P-1, ale až při změně na stav P0, tím pádem není od čeho odvozovat, kdy záznam vzniknul; jako nejjednodušší řešení mi přijde posunout trigger pro vytvoření záznamu PX0 v historii tak, aby se zapsal hned se zápisem projektu do P-1 a nečekal až na posun do P0. Vadit by to ničemu nemělo.
- [ ] Na nějaký healthcheck to padá nadále - tentokrát se to stalo kvůli `cancel_old_projects` (úloha jako taková běží ok); i když se vyhneme situacím, kdy toho nebude tolik najednou, aplikace by neměla být kvůli naplánovaným úlohám potenciálně takto nestabilní. Myslím že to bude stále souviset s healthcheck celery nebo redis. Aplikace si zjevně myslí, že něco nejede a snaží se stále dokola restartovat. Přitom žádný reálný problém nemá.

**Comment by pesikj** [comment]
@motyc 

>  change_document_accessibility - nepodařilo se mi rozjet, nic neudělalo; asi bude nějaká chyba v podmínce, ale nevidím ji

Není tahle podmínka obráceně?

```py
if pristupnost_razeni < az_pristupnost_razeni:
```

**Comment by motyc** [comment]
@pesikj To by mělo být myslím dobře. Ta logika je, že se přístupnost nastaví podle organizace (pristupnost_razeni = item.organizace.zverejneni_pristupnost.razeni), ale nikdy ne níže, než je přístupnost napojených AZ (az_pristupnost_razeni = min(*[x.archeologicky_zaznam.pristupnost.razeni for x in item.casti.all()])). Tj. i když by bylo v organizaci A, tak pokud minimum v akcích C, musí se to nastavit na C.

**Comment by motyc** [comment]
### Test Test v1.0.0-RC4
Aktualizace:
- [ ] `delete_reporter_data_ten_years` - metadata se vytvoří příliš brzy, změna se v nich neprojeví (jinak ok)
- [ ] `change_document_accessibility` - nepodařilo se mi rozjet, nic neudělalo; asi bude nějaká chyba v podmínce, ale nevidím ji
- [ ] `send_notifications_en` - tady se také nic nepošle, ale myslím, že vím i důvod - ptáme se na `historie__historie__datum_zmeny=timezone.now().date() + timedelta(days=-1)`, jenže `historie__historie__datum_zmeny` je timestamp - muselo by se to tedy trefit na naprosto přesný čas. Je tedy třeba upravit podmínku buď tak, aby historie__historie__datum_zmeny bylo ořezáno na dtum, nebo se to ptalo nějak takto =`datum_zmeny > (CURRENT_DATE - INTERVAL '2 day') AND datum_zmeny < (CURRENT_DATE)` - **_oprava patrně nepomohla_**
- [ ] `delete_unsubmited_projects` - úprava chování historie je, ale samotná funkce nefunguje; podle logu Fedory se pouze vytvoří prázdná transakce, ale nic se do ní dál již nepošle. Výběr projektů by měl odpovídat:
```plpgsql
SELECT * FROM projekt
	JOIN historie ON projekt.historie = historie.vazba
WHERE stav = -1 AND historie.datum_zmeny < (now() - INTERVAL '12 hour');
```

**Comment by pesikj** [comment]
@motyc

> úprava chování historie je ok, ale samotná funkce nefunguje; podle logu Fedory se pouze vytvoří prázdná transakce, ale nic se do ní dál již nepošle. Výběr projektů by měl odpovídat:

Tady je problém v tom, že projekt s napojenými soubory není možné smazat, brání tomu podmínka v signálu.

**Comment by motyc** [comment]
@pesikj Aha. A šlo by tedy v tomto případě nejdřív postupně zavolat smazání souborů a pak až mazání projektu?

**Comment by pesikj** [comment]
>  delete_reporter_data_ten_years - metadata se vytvoří příliš brzy, změna se v nich neprojeví (jinak ok)

Oprava testována na

- http://localhost:8000/projekt/detail/C-201446740
- https://fedora-test.aiscr.cz/rest/AMCR/record/C-201446740/metadata/fcr:metadata

**Comment by pesikj** [comment]
@motyc 

> Aha. A šlo by tedy v tomto případě nejdřív postupně zavolat smazání souborů a pak až mazání projektu?

Pokud je to žádoucí, tak samozřejmě ano.

**Comment by motyc** [comment]
@pesikj Ano, lze je v tomto případě zlikvidovat. Jsou to polotovary, které již nikdy nikdo nedokončí. Pro ostatní projekty samozřejmě tu ochranu ponechte.

**Comment by motyc** [comment]
### Test Test v1.0.0-RC4
Aktualizace:
- [ ] `change_document_accessibility` - nepodařilo se mi rozjet, nic neudělalo; asi bude nějaká chyba v podmínce, ale nevidím ji. Zjednodušený dotaz pro testování (neobsahuje podmínku na přístupnost napojených AZ):
```plpgsql
SELECT * FROM dokument d
	JOIN dokument_cast dc ON dc.dokument = d.id
	JOIN organizace o ON o.id = d.organizace
	JOIN heslar h1 ON o.zverejneni_pristupnost = h1.id
	JOIN heslar h3 ON d.pristupnost = h3.id
WHERE datum_zverejneni < now() AND h3.razeni > h1.razeni
``` 
- [ ] `send_notifications_en` - stále nefunkční; pro test používám tyto dva dotazy (i když dotazy data vrátí, spuštění úlohy nic nepošle):
```plpgsql
SELECT DISTINCT sn.ident_cely, u.email FROM samostatny_nalez sn
	JOIN projekt pr ON sn.projekt = pr.id
	JOIN historie h1 ON sn.historie = h1.vazba
	JOIN historie h2 ON sn.historie = h2.vazba
	JOIN uzivatel_spoluprace s ON h1.uzivatel = s.spolupracovnik
	JOIN auth_user u ON s.vedouci = u.id
	JOIN auth_user_notifikace_typ un ON u.id = un.user_id
	JOIN notifikace_typ nt ON un.usernotificationtype_id = nt.id
WHERE h1.typ_zmeny = 'SN01' AND pr.organizace = u.organizace AND nt.ident_cely = 'S-E-N-01' AND h2.typ_zmeny = 'SN12'
	AND h2.datum_zmeny > (CURRENT_DATE - INTERVAL '2 day') AND h2.datum_zmeny < (CURRENT_DATE);

SELECT DISTINCT sn.ident_cely, u.email FROM samostatny_nalez sn
	JOIN historie h1 ON sn.historie = h1.vazba
	JOIN historie h2 ON sn.historie = h2.vazba
	JOIN auth_user u ON h1.uzivatel = u.id
	JOIN auth_user_notifikace_typ un ON u.id = un.user_id
	JOIN notifikace_typ nt ON un.usernotificationtype_id = nt.id
WHERE h1.typ_zmeny = 'SN01' AND nt.ident_cely = 'S-E-N-02' AND h2.typ_zmeny = 'SN34'
	AND h2.datum_zmeny > (CURRENT_DATE - INTERVAL '2 day') AND h2.datum_zmeny < (CURRENT_DATE);
``` 
- [ ] `delete_unsubmited_projects` - projekty se smazaly, ale nijak se neupravila data ve Fedoře. Výběr projektů by měl odpovídat (to sedí):
```plpgsql
SELECT * FROM projekt
	JOIN historie ON projekt.historie = historie.vazba
WHERE stav = -1 AND historie.datum_zmeny < (now() - INTERVAL '12 hour');
``` 
Log Fedory:
![image](https://github.com/user-attachments/assets/595c4cb8-607f-481d-b878-b43f5e4ff65d)
První rollback je ok, protože projekt ve Fedoře není, ale druhá transakce by projít měla. Chybí v ní ale všechny kroky mazání (kontejner záznamu a proxy by se měly celé odstranit bez náhrady - zbydou jen tombstone).

**Comment by motyc** [comment]
### Test v1.0.3
- [ ] drobné optimalizace jsem dal do #2184
- [ ] `change_document_accessibility` - už jsme se významně posunuli - podařilo se mi to rozjet a udělalo to přesně, co mělo (pravidla se správně aplikovala na očekávané záznamy). Následně jsem však změnil výchozí přístupnost u jedné z organizací na anonyma (ORG-000111), díky čemuž by se měla následně po novém běhu změnit řada záznamů - to se ale nestalo. Nemůže tam být nějaký problém v používání cache? Jinak mě nenapadá, co by to mohlo způsobovat. Příklad dokumentu, na který se teď funkce neaplikuje, přestože by měla: https://amcr-test.aiscr.cz/dokument/detail/M-TX-198401579 (po změně u ORG-000111 by měla být přístupnost A). I jiné editace dělají problém (např. jsem záznamu https://amcr-test.aiscr.cz/dokument/detail/X-M-TX-201800727 změnil organizaci a doplnil datum zveřejnění a ani ten to správně nevyhodnotí.
```plpgsql
SELECT * FROM dokument d
	JOIN dokument_cast dc ON dc.dokument = d.id
	JOIN organizace o ON o.id = d.organizace
	JOIN heslar h1 ON o.zverejneni_pristupnost = h1.id
	JOIN heslar h3 ON d.pristupnost = h3.id
WHERE datum_zverejneni < now() AND h3.razeni > h1.razeni
``` 
- [ ] `send_notifications_en` - stále se mi nedaří donutit aplikaci cokoli poslat - testuji tak, že měním v DB datum v historii záznamu (např. u C-202109132-N00725 a C-202313308-N00005, ale i jiné). Ani v jednom případě se mi nepodařilo aplikaci donutit něco odeslat, a to jsem zkoušel měnit datum v rozpětí tří dnů, aby jsem se do intervalu s jistotou trefil. Buď je tedy také nějaký problém s cache a změny v DB funkce neregistruje, nebo je tam stále nějaká chyba. Logu i Celery aktivitu vidím, ale mailtrap i související log se nezmění. @jhavrlant - prosím, mrkni na to také, zde už se hodně točíme v kruhu.
```plpgsql
SELECT DISTINCT sn.ident_cely, u.email FROM samostatny_nalez sn
	JOIN projekt pr ON sn.projekt = pr.id
	JOIN historie h1 ON sn.historie = h1.vazba
	JOIN historie h2 ON sn.historie = h2.vazba
	JOIN uzivatel_spoluprace s ON h1.uzivatel = s.spolupracovnik
	JOIN auth_user u ON s.vedouci = u.id
	JOIN auth_user_notifikace_typ un ON u.id = un.user_id
	JOIN notifikace_typ nt ON un.usernotificationtype_id = nt.id
WHERE h1.typ_zmeny = 'SN01' AND pr.organizace = u.organizace AND nt.ident_cely = 'S-E-N-01' AND h2.typ_zmeny = 'SN12'
	AND h2.datum_zmeny >= (CURRENT_DATE - INTERVAL '1 day') AND h2.datum_zmeny < (CURRENT_DATE);

SELECT DISTINCT sn.ident_cely, u.email FROM samostatny_nalez sn
	JOIN historie h1 ON sn.historie = h1.vazba
	JOIN historie h2 ON sn.historie = h2.vazba
	JOIN auth_user u ON h1.uzivatel = u.id
	JOIN auth_user_notifikace_typ un ON u.id = un.user_id
	JOIN notifikace_typ nt ON un.usernotificationtype_id = nt.id
WHERE h1.typ_zmeny = 'SN01' AND nt.ident_cely = 'S-E-N-02' AND h2.typ_zmeny = 'SN34'
	AND h2.datum_zmeny >= (CURRENT_DATE - INTERVAL '1 day') AND h2.datum_zmeny < (CURRENT_DATE);
``` 
- [ ] `delete_unsubmited_projects` - už se blížíme, ale stále to není podle zadání - projekty se smazaly, ale ve Fedoře nedojde ke komplentímu odstranění ([jen se označí jako "deleted"](https://fedora-test.aiscr.cz/rest/AMCR/record/X-C-000001025), což ale nechceme; např. ). Zdůrazním totéž, co minule: _kontejner záznamu a proxy by se měly celé odstranit bez náhrady - zbydou jen tombstone_ - teď to naopak zafungovalo tak, že se do Fedory zapsal [i projekt v P-1](https://fedora-test.aiscr.cz/rest/AMCR/record/X-C-000001026), který tam před tím nebyl.
```plpgsql
SELECT * FROM projekt
	JOIN historie ON projekt.historie = historie.vazba
WHERE stav = -1 AND historie.datum_zmeny < (now() - INTERVAL '12 hour');
```

**Comment by pesikj** [comment]
>  stále se mi nedaří donutit aplikaci cokoli poslat - testuji tak, že měním v DB datum v historii záznamu (např. u C-202109132-N00725 a C-202313308-N00005, ale i jiné). Ani v jednom případě se mi nepodařilo aplikaci donutit něco odeslat, a to jsem zkoušel měnit datum v rozpětí tří dnů, aby jsem se do intervalu s jistotou trefil. Buď je tedy také nějaký problém s cache a změny v DB funkce neregistruje, nebo je tam stále nějaká chyba v odesílání samotném. V logu i Celery aktivitu vidím, ale mailtrap i související log se nezmění. @jhavrlant - prosím, mrkni na to také, zde už se hodně točíme v kruhu.

Pro SN01 není v historii žádný záznam v potřebném intervalu, takže se nic odeslat nemohlo.

![image](https://github.com/user-attachments/assets/a417bccb-f105-4ac7-878f-2bd15062dc51)

Pokud datum nastavím správně, odesílání notifikací je vidět v logu.

![image](https://github.com/user-attachments/assets/5d305bb0-2fbb-4725-844e-291ad41dad87)

![image](https://github.com/user-attachments/assets/7b79f2d3-5eaf-475c-a91f-8bb882cf5399)

**Comment by pesikj** [comment]
@motyc 

> change_document_accessibility - už jsme se významně posunuli - podařilo se mi to rozjet a udělalo to přesně, co mělo (pravidla se správně aplikovala na očekávané záznamy). Následně jsem však změnil výchozí přístupnost u jedné z organizací na anonyma (ORG-000111), díky čemuž by se měla následně po novém běhu změnit řada záznamů - to se ale nestalo. Nemůže tam být nějaký problém v používáním cache? Jinak mě nenapadá, co by to mohlo způsobovat. Příklad dokumentu, na který se teď funkce neaplikuje, přestože by měla: https://amcr-test.aiscr.cz/dokument/detail/M-TX-198401579 (po změně u ORG-000111 by měla být přístupnost A). I jiné editace dělají problém - např. jsem záznamu https://amcr-test.aiscr.cz/dokument/detail/X-M-TX-201800727 změnil organizaci a doplnil datum zveřejnění a ani ten to správně nevyhodnotí.

Přidal jsem invalidaci cache. Nevím, jestli v důsledku toho, ale po spuštění proběhla velká řada operací.

**Comment by motyc** [comment]
@pesikj `send_notifications_en` - no jo, z Vaší odpovědi už je mi jasné, co je problém - pro E-N-01 datum vztahujete k posunu SN01 (zápis nálezu), jenže to má být vztaženo k SN12 (odeslání nálezu) - mrkněte na to SQL, z toho je to myslím jasné. Podobně pro E-N-01 se to musí brát z SN34. Ze SN01 se jen určitým způsobem odvozují adresáti, ale na tomto datu vůbec nezáleží... Proto mi to nikdy nic neposlalo, protože jsem upravoval správné stavy. Koukám ale do kódu, a tam se v tom moc nevyznám, kde by přesně měla být chyba. Zjevně se tam ale nějak dotčené datumy míchají.

**Comment by pesikj** [comment]
@motyc Datum se filtruje vždy podle toho, u jakého typu záznamu v historii je napsaný. Teď už by to snad mělo být správně.

![image](https://github.com/user-attachments/assets/9e75a753-d493-418b-bb58-fb586e1bf744)

![image](https://github.com/user-attachments/assets/d21e9650-4f0f-4d5f-a5a5-f4764be8d100)

**Comment by motyc** [comment]
@pesikj Ano, souhlas. SN34 opravil vas commit, SN12 jsem opravil ja v tom posladnim. Tak snad jsme to konecne vyresili :)

**Comment by motyc** [comment]
@pesikj Dejte si panáka, zavírám...
