### ISSUE TITLE
Výsledky revize stavu struktury DB

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#474]
Byla provedena kompletní revize stavu DB ve verzi k týdnu od 16. 5. 2022. Na základě testování předkládám seznam nutných oprav a optimalizací. Jsou to většinou menší problémy, ale jejich vyřešení zabrání možným chybám a nekonzistencím. Opravy je nutno zanést do migrací.

### adb
- [ ] dokumentacni_jednotka – není unique constraint zbytečný, když jde o PK?

### akce
- [ ] archeologicky_zaznam – není unique constraint zbytečný, když jde o PK?
- [x] organizace – chybí FK na organizace.id

### akce_vedouci
- [ ] organizace – chybí not null (souvisí s nedodělanou migrací), LZE DOKONČIT AŽ PO MIGRACI
- [x] id – patrně z praktických důvodů doplněno, pak ale dát jako PK místo stávající kombinace polí vedouci + organizace (z nich udělat kombinovanou unique constraint)

### archeologicky_zaznam
- [x] ident_cely
- chybí not null
- chybí unique constraint
- [x] stav_stary – pole navíc (lze odstranit, pozůstatek migrace)
- [x] historie – chybí unique constraint

### archeologicky_zaznam_katastr
- [x] id – patrně z praktických důvodů doplněno, pak ale dát jako PK místo stávající kombinace polí archeologicky_zaznam + katastr (z nich udělat kombinovanou unique constraint)

### auth_user REMOVED
- [ ] auth_level – obsahuje oprávnění podle staré AMČR;  částečně promítnuto do hlavni_role, ale půjde smazat ve chvíli, kdy dojde k plné migraci oprávnění, na to je ale třeba dodělat #379 (a související issue)
- [ ] email_potvrzen – potřebujeme? obsahuje návratové kódy k ověření mailu ve staré AMČR
- [ ] email – chybí unique constraint
(případné změny je třeba promítnout též do uzivatel_historicaluser, kam se data verzují)

### dokument
- [x] soubory – chybí unique constraint
- [x] historie – chybí unique constraint

### dokument_autor
- [x] id – patrně z praktických důvodů doplněno, pak ale dát jako PK místo stávající kombinace polí dokument + autor (z nich udělat kombinovanou unique constraint)
- [x] chybí unique constraint na kombinaci dokument + poradi

### dokument_cast
- [x] archeologicky_zaznam – smazat comment

### dokument_jazyk
- [x] chybí unique constraint na kombinaci dokument + jazyk

### dokument_osoba
- [x] id – patrně z praktických důvodů doplněno, pak ale dát jako PK místo stávající kombinace polí dokument + osoba (z nich udělat kombinovanou unique constraint)

### dokument_posudek
- [x] chybí unique constraint na kombinaci dokument + posudek

### dokument_sekvence
- [x] id – chybí nastavení jako PK
- zbytek řešen v: https://github.com/ARUP-CAS/aiscr-webamcr/issues/732

### dokumentacni_jednotka
- [x] komponenty – chybí unique constraint
- [x] ident_cely - chybí not null

### externi_odkaz
- [x] externi_zdroj – chybí not null
- [x] archeologicky_zaznam – chybí not null

### externi_zdroj
- [x] final_cj – odstranit (ani jinde nakonec zjevně nepoužíváme)
- [x] historie – chybí unique constraint
- [x] ident_cely - chybí not null

### externi_zdroj_autor
- [ ] v rámci konzistence doplnit: id integer NOT NULL DEFAULT nextval('externi_zdroj_autor_id_seq'::regclass)
- [ ] id nastavit jako PK
- [x] doplnit unique constraint na kombinaci externi_zdroj + autor
- [x] chybí unique constraint na kombinaci externi_zdroj + poradi

### externi_zdroj_editor
- [x] v rámci konzistence doplnit: id integer NOT NULL DEFAULT nextval('externi_zdroj_editor_id_seq'::regclass)
- [x] id nastavit jako PK
- [x] doplnit unique constraint na kombinaci externi_zdroj + editor

### heslar
- [ ] ident_cely – chybí not null - LZE DOKONČIT PO NOVÉ MIGRACI
- [x] heslo – chybí not null
- [x] heslo_en – chybí not null
- [x] puvodni_id – navíc (na konci migrace vždy smazat)
- [x] chybí unique constraint na kombinaci nazev_heslare + heslo
- [x] chybí unique constraint na kombinaci nazev_heslare + heslo_en

### heslar_datace
- [x] úpravy viz https://github.com/ARUP-CAS/aiscr-webamcr/issues/386

###  heslar_dokument_typ_material_rada
- [x] validated – má být odstraněno
- [x] zrušit nadbytečný constraint heslar_typ_material_rada_heslar_rada_id_heslar_typ_dokumentu_id

### heslar_hierarchie
- [x] v rámci konzistence doplnit: id integer NOT NULL DEFAULT nextval('heslar_hierarchie_id_seq'::regclass)
- [x] id nastavit jako PK
- [x] doplnit unique constraint na kombinaci heslo_podrazene + heslo_nadrazene + typ

### historie
- [x] typ_zmeny_old – navíc (na konci migrace vždy smazat)

### komponenta
- [x] komponenta_vazby – chybí not null

### komponenta_aktivita
- [x] id – patrně z praktických důvodů doplněno, pak ale dát jako PK místo stávající kombinace polí komponenta + aktivita (z nich udělat kombinovanou unique constraint)

### let
- [x] ident_cely - chybí not null

### lokalita
- [x] archeologicky_zaznam – není unique constraint zbytečný, když jde o PK?

### nalez_objekt
- [x] id – chybí nastavení jako PK

### nalez_predmet
- [x] id – chybí nastavení jako PK

### neident_akce
- [x] id – odstranit
- [x] dokument_cast
- nastavit na PK
- unique constraint se stane zbytečným – zrušit
- chybí not null
- [x] ident_cely - odstranit, vždy bude stejné jako u dokument_cast (v zadání opomenuto)

### neident_akce_vedouci
- [x] v rámci konzistence doplnit: id integer NOT NULL DEFAULT nextval('neident_akce_vedouci_id_seq'::regclass)
- [x] id nastavit jako PK
- [x] doplnit unique constraint na kombinaci neident_akce + vedouci

### notifikace_projekt
- [x] chybí PK - doplnit: id integer NOT NULL DEFAULT nextval('notifikace_projekt_id_seq'::regclass)

### organizace
- [x] nazev_zkraceny_en – chybí not null
- [x] ident_cely (text, not null, unique) – zcela chybí (formát ORG-123456, běžná sekvence)
- [ ] nazev_zkraceny – chybí unique constraint

### osoba
- [x] ident_cely (text, not null, unique) – zcela chybí (formát OS-123456, běžná sekvence)

### oznamovatel
- [ ] id je zbytečné, smazat a jako PK nastavit pole projekt (u něj pak bude nadbytečný unique constrain)

### pian
- [x] historie – chybí unique constraint

### projekt
- [x] planovane_zahajeni_text – smazat (bude se muset převést před migrací)
- [x] ident_cely – chybí not null
- [x] soubory – chybí unique constraint
- [x] historie – chybí unique constraint

### projekt_katastr
- [x] id – patrně z praktických důvodů doplněno, pak ale dát jako PK místo stávající kombinace polí projekt_id + katastr_id (z nich udělat kombinovanou unique constraint)

### projekt_sekvence
- [x] id – chybí nastavení na PK

### ruian_katastr
- [x] hranice – chybí not null
- [x] poznamka – odstranit
- [ ] nazev – doplnit unique constraint (nepůjde před #372)
- [ ] kod – doplnit unique constraint (nepůjde před #372)
- [x] pian – doplnit unique constraint
další úpravy až v rámci https://github.com/ARUP-CAS/aiscr-webamcr/issues/372

### ruian_kraj
- [x] aktualni – odstranit
- [ ] definicni_bod – chybí not null (nepůjde nastavit - chybí data - musí řešit ARÚ)
- [ ] hranice – chybí not null (nepůjde nastavit - chybí data - musí řešit ARÚ)
- [x] nazev_en (not null) – doplnit - opomenuto v zadání

### ruian_okres
- [x] aktualni – odstranit
- [x] nazev_en – chybí not null
- [ ] definicni_bod – chybí not null (nepůjde nastavit - chybí data - musí řešit ARÚ)  (nepůjde před #372)
- [ ] hranice – chybí not null (nepůjde nastavit - chybí data - musí řešit ARÚ)  (nepůjde před #372)
- [x] nazev – doplnit unique constraint
- [x] kod – doplnit unique constraint
- [x] spz – doplnit unique constraint

### samostatny_nalez
- [x] pristupnost – default nemůžeme stanovovat pomocí ID, ale selectem („C“, z hesláře přístupnost), ID není významová konstanta a může vzniknout zcela chybný záznam - otázka je, zda raději neřešit v aplikaci
- [x] ident_cely – chybí not null
- [x] soubory – chybí unique constraint
- [x] historie – chybí unique constraint

### stats_login
- [x] odstranit, nepotřebujeme (EDIT: před odstraněním zvážit migraci dat - viz https://github.com/ARUP-CAS/aiscr-webamcr/issues/269#issuecomment-1302355340)

### uzivatel
- [x] odstranit, nepotřebujeme (vše je nyní v auth_user)

### uzivatel_notifikace
- [x] v rámci konzistence doplnit: id integer NOT NULL DEFAULT nextval('uzivatel_notifikace_id_seq'::regclass)
- [x] id nastavit jako PK

### uzivatel_spoluprace
- [x] historie – chybí unique constraint

### vyskovy_bod
- [x] řeší se v rámci https://github.com/ARUP-CAS/aiscr-webamcr/issues/373
- northing – odtsranit
- easting – odstranit
- niveleta – odstranit
- [x] poradi – odstranit
- [x] id – chybí nastavení na PK

**Comment by pesikj** [comment]
@motyc @ScottVanWagenen 
Toto je oprava struktury databáze. Nevím, k jakému předchozímu issue nebo objednávce se to váže, takže nedokážu posoudit, zda jde o bug nebo požadavek na změnu.

**Comment by motyc** [comment]
@pbartosova Ještě doplňuji dotaz k tabulkám `notifikace`, `projekt_oznameni_suffix`, `systemove_promenne` - používají se někde, nebo nakonec ne? Mám tokový dojem, že nikoli. Pokud ne, navrhoval bych je také odstranit.

**Comment by pbartosova** [comment]
Nerozumím zadání bodu:
akce - Chybné řešení pro datumy - Prosím řešme pouze strukturu DB, nepatří sem migrace

datum_zahajeni_v – chybí v DB (asi omylem odstraněno) - Tento sloupec má přece zaniknout, tak tu správně není
datum_ukonceni_v – chybí v DB (asi omylem odstraněno) - Tento sloupec má přece zaniknout, tak tu správně není
datum_zahajeni – date místo text?  ANO date dle požadavků
datum_ukonceni – date místo text? ANO date dle požadavků

**Comment by motyc** [comment]
@pbartosova Máš úplnou pravdu. Omlouvám se, ale zde jsem opravdu udělal chybu já a špatně jsem si pamatoval, na čem jsem se domluvili ohledně řešení v DB (hlavně jsem si to nezanesl do své dokumentace). Je to implementováno sprváně, v prvním příspěvku to odstraním.

**Comment by pbartosova** [comment]
Toto zadání se opakuje
" id – patrně z praktických důvodů doplněno, pak ale dát jako PK místo stávající kombinace polí vedouci + organizace (z nich udělat kombinovanou unique constraint)" 
a nejsem si jistá, zda rozumím zadání.

@motyc Prosím o revizi této položky pro table akce_vedouci, pak už vezmu analogicky:
ALTER TABLE akce_vedouci DROP CONSTRAINT akce_vedouci_pkey;    
ALTER TABLE akce_vedouci ADD CONSTRAINT akce_vedouci_pkey PRIMARY KEY (id);   
ALTER TABLE akce_vedouci ADD CONSTRAINT akce_vedouci_akce_vedouci_fkey UNIQUE (akce, vedouci);

Sekvence tedy zůstanou apod.

**Comment by motyc** [comment]
@pbartosova
> ALTER TABLE akce_vedouci DROP CONSTRAINT akce_vedouci_pkey;
OK
> ALTER TABLE akce_vedouci ADD CONSTRAINT akce_vedouci_pkey PRIMARY KEY (id);
OK
>ALTER TABLE akce_vedouci ADD CONSTRAINT akce_vedouci_akce_vedouci_fkey UNIQUE (akce, vedouci);
Zde nevím, zda je to vhodné označovat "*_fkey", když jde o unique constraint... Např. v uzivatel_spoluprace máme totéž označeno jen "*_key".

**Comment by pbartosova** [comment]
Děkuji za revizi. Platí, že UNIQUE key budou s _key, fkey je pro foreign key. Private key by měly mít _pkey. Platí ale pouze pro nová pravidla, historicky jsou některé key pojmenovány různě.

**Comment by pbartosova** [comment]
Většina tasků je dokončena. Chybí jen ty, co jsou závislá na opravě dat, které řeší jiná issue. 
Chybí části pro odstranění sloupců v DB, sql příkazy jsou připraveny, nejdříve je nutné nasadit feature/474-hotfix.  V době testování ale už není doporučeno na test zasahovat. 
Constraint, které se váží na pole, které mají i primary key, db smazat nedovolí.

**Comment by motyc** [comment]
@pbartosova Prověřím to, ale asi to budou sirotci ke smazání...

**Comment by pbartosova** [comment]
Objevila se kolize s požadavkem issue #48 . evidujeme foreign key v tabulce neident_akce_vedouci na neident_akce(id), která ale má být odstraněno. @motyc prosím o návrh řešení. 
Obecně nechápu, proč někde id mažeme a někde ho zase přidáváme jen kvůli konsitenci? Neměly by tedy id zůstat u všech tabulek?

**Comment by motyc** [comment]
@pbartosova
ad neident - FK lze přemapovat na neident_akce.dokument_cast;
nevím, kde to bude nejsnazší řešit pro migrace (teoreticky lze dopsat nový převod), ale možná by to stačilo řešit úpravou zde:
https://github.com/ARUP-CAS/aiscr-webamcr/blob/4a0a5f9fdbeec39bda22141dc57d4b08db4ed247/migrace/migrace_4.sql#L139

a zde:
https://github.com/ARUP-CAS/aiscr-webamcr/blob/48218d29eea99910e5fdb1fba4a9132a1552e3a7/migrace/40_migrace_revize_cizich_klicu_create.sql#L129

**Comment by pbartosova** [comment]
Nejde ale jen o přemapování foreign_key. Tabulka neident_akce_vedouci.neident_akce obsahuje id tabulky neident_akce. Nejde tedy o chybějící foreing key, ale i o opravu dat.

**Comment by motyc** [comment]
@pbartosova Ano, to je samozřejmě pravda.

**Comment by pbartosova** [comment]
Udělám večer, abych to neměnila někomu pod rukama.

**Comment by pbartosova** [comment]
Tyto body navrhuji přenést do nového issue:
 adb.dokumentacni_jednotka – není unique constraint zbytečný, když jde o PK?
 akce.archeologicky_zaznam – není unique constraint zbytečný, když jde o PK?
akce_vedouci.organizace – chybí not null (souvisí s nedodělanou migrací), LZE DOKONČIT AŽ PO MIGRACI
heslar. ident_cely – chybí not null - LZE DOKONČIT PO NOVÉ MIGRACI
projekt. planovane_zahajeni_text – smazat sloupec (bude se muset převést před migrací)
ruin_kraj.definicni_bod – chybí not null (nepůjde nastavit - chybí data - musí řešit ARÚ)
ruin_kraj.hranice – chybí not null (nepůjde nastavit - chybí data - musí řešit ARÚ)
stats_login - odstranit tabulku, nepotřebujeme (EDIT: před odstraněním zvážit migraci dat - viz https://github.com/ARUP-CAS/aiscr-webamcr/issues/269#issuecomment-1302355340)

**Comment by pbartosova** [comment]
Prosím o revizi a zavření issue.
