### ISSUE TITLE
Ladění zobrazení popisků v mapách

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#508]
Při zobrazení mapy je třeba po kliknutí zobrazit tooltip a umožnit přechod na související záznam v tooltipu:
- [x] vrstvy s projekty
-- při najetí zobrazit "`projekt.ident_cely` (`projekt.stav`)"
-- při kliknutí zobrazit `projekt.ident_cely` s proklikem na konkrétní záznam v novém tabu
- [x] vrstvy se samostatnými nálezy
-- při najetí zobrazit `samostatny_nalez.ident_cely`
-- zobrazit `samostatny_nalez.ident_cely` s proklikem na konkrétní záznam v novém tabu
- [x] vrstvy s dokumenty 3D
-- při najetí zobrazit `dokument.ident_cely`
-- při kliknutí zobrazit `dokument.ident_cely` s proklikem na konkrétní záznam v novém tabu
- [x] vrstvy s PIAN
-- [x] při najetí na PIAN "`pian.ident_cely` (`pian.presnost`)"
-- [x] při najetí na definiční bod zobrazit "`pian.ident_cely` (`pian.presnost`) - centroid"
-- [ ] při kliknutí (na PIAN i jeho definiční bod) zobrazit `dokumentacni_jednotka.ident_cely` (všechny napojené) s proklikem na konkrétní záznam v novém tabu

Popisek po najetí:
![image](https://user-images.githubusercontent.com/20186892/198274482-85b2abfc-f761-4a33-974e-eda2cc37f055.png)

Menu po kliknutí (nyní jen text, bude hyperlink):
![image](https://user-images.githubusercontent.com/20186892/198274187-56d15074-3f8f-4758-9eec-c8b29a759709.png)

**Comment by jiri-bartos-huld** [comment]
@pesikj Toto stale neni dodelano:
[1-3] by nemeli byt tezke
[4] bude slozitejsi: dohledat vsechny dj k pianu (tohle bude muset byt pres Ajax pr konkretni pian)+je zde problem, ze klik uz je rezervovany pro vyber pianu z mapy (zde se nam to "koliduje" s tim popupem-nevim zda to pujde)

**Comment by motyc** [comment]
@jiri-bartos-huld A nešlo by ten klik rezervovaný pro výběr PIAN z mapy upravit tak, že by se něco jako "Připojit" objevilo přímo v tooltipu PIAN, takže by člověk nejdříve kliknul na PIAN, otevřel by se tooltip a v něm by pak potvrdil, že to chce připojit? Je úplně jedno, že by v tooltip byly i další informace o napojených DJ (resp. to by naopak byla výhoda).

**Comment by jiri-bartos-huld** [comment]
Nakonce se podarilo vyresit tu kolizi v clicku: normalne by to melo zobrazovat popup, pouze kdyz uzivatel vybira pian z mapy do Dj tak se popup nezobrazi:
![obrazek](https://github.com/ARUP-CAS/aiscr-webamcr/assets/77389730/f10afa2c-32dc-4f2f-bbc2-610bf7eddf24)

**Comment by jiri-bartos-huld** [comment]
priparaveno na MR

**Comment by motyc** [comment]
Nelze testovat kvůli #1342

**Comment by motyc** [comment]
### Test v0.3.5z29
- [ ] Pokud kliknu na PIAN patřící k právě zvolené DJ, zobrazí se jen prázdný tooltip a v tooltipu po najetí je místo identu PIAN ident DJ:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/7b552c20-d5c3-48a8-bfb4-5aa45e79232a)
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/47338491-47b8-45bc-90a7-68acdd98a7c5)
- [ ] Kliknutí na centroid sice zobrazí ident navázené DJ, ale není to hyperlink. Tooltip po najetí podle zadání se nezobrazí vůbec.
- [ ] Projekty - tooltip u bodu vymezujícího projekt se zobrazí až na kliknutí, zobrazoval bych normálně i tooltip přímo po najetí (se stejným obsahem vázaným na Rosettu).
- [ ] PAS - tooltip u bodu vymezujícího nález není vůbec. Řešit jako pro projekt.
- [ ] 3D nyní neotestuji kvůli chybě v #558

**Comment by jiri-bartos-huld** [comment]
Priprava:
- Projekty - tooltip u bodu vymezujícího projekt se zobrazí až na kliknutí, zobrazoval bych normálně i tooltip přímo po najetí (se stejným obsahem vázaným na Rosettu).
-- při najetí zobrazit "projekt.ident_cely (projekt.stav)"
-- při kliknutí zobrazit projekt.ident_cely BEZ prokliku na konkrétní záznam v novém tabu
-PAS - tooltip u bodu vymezujícího nález není vůbec. Řešit jako pro projekt.
-- při najetí zobrazit "projekt.ident_cely"
-- při kliknutí zobrazit projekt.ident_cely BEZ prokliku na konkrétní záznam v novém tabu
-http://192.168.254.30:8080/arch-z/akce/detail/C-9126062A - při najetí na bod PAS se nyní nezobrazí nic, po kliknutí se otevře tooltip, ale bez hyperlinku:
-- při najetí zobrazit "ident_cely (projekt.stav)"
-- při kliknutí zobrazit ident_cely s proklikem na konkrétní záznam v novém tabu

**Comment by jiri-bartos-huld** [comment]
@pesikj @motyc 
pripraveno na MR

**Comment by motyc** [comment]
@jiri-bartos-huld

Korekce k předchozímu příspěvku od Vás, protože jsme se vůbec nepochopili - k aktuálnímu projektu jsem myslel, aby se zobrazilo to, co tam již bylo, tj. text podle klíče z překladů v Rosseta, kde se píše, že jde o aktuálně editovaný projekt. Problém byl pouze v tom, že se tooltip nezobrazil dříve, než když jsem na bod kliknul. Nemělo se to předělávat úplně, to jsem nepožadoval.

Totéž platí pro PAS a 3D. Rozhodě se tam nemají motat další ID, natož pak ID z projektů.

**Comment by motyc** [comment]
@jiri-bartos-huld Nejlepší by bylo, kdybychom měli pro každý samostatný klíč, tj. např.:
- mapa.lokalizaceProjektu
- mapa.lokalizacePAS
- mapa.lokalizace3D

Myslím si, že mapa.lokalizaceZamer bylo původně jen pro http://192.168.254.30:8080/oznameni/, což by bylo fajn mít také takto oddělené.

Jinak to sedí a děkuji.

**Comment by jiri-bartos-huld** [comment]
@motyc opraveno pripraveno na MR

**Comment by motyc** [comment]
### Test v0.3.5z67
Něco opraveno, ale:
- [ ] _Kliknutí na centroid sice zobrazí ident navázené DJ, ale není to hyperlink. Tooltip po najetí podle zadání se nezobrazí vůbec._ - centroidy se nyní vůbec nezobrazují (test u http://192.168.254.30:8080/arch-z/akce/detail/C-9126062A/dj/C-9126062A-D01). Navíc vůbec neodpovídá barevná symbologie (viz #302), která teď částečně funguje jen pro body (žluté označení, zelené nikoli).
- [ ] _PAS - tooltip u bodu vymezujícího nález není vůbec. Řešit jako pro projekt._ - nyní se zobrazí jen prázdný label i tooltip; tipuji, že neproběhlo doplnění klíče do html template
- [ ] _3D - tooltip u bodu vymezujícího model se zobrazí až na kliknutí, zobrazoval bych normálně i tooltip přímo po najetí (se stejným obsahem vázaným na Rosettu)._ - asi podobný problém jako v PAS, jen tady se záznam ani neotevře (http://192.168.254.30:8080/dokument/model/detail/C-3D-202300002)
- [ ] U importovaných PIAN (viz Uživatelský import geometrie PIAN #298) zbylo: _po kliknutí vyskakuje (logicky) prázdný tooltip, protože importovaný PIAN nemá a nemůže mít žádná napojení, neměl by se tak zbytečně otevírat (kliknutí nemusí dělat nic)_

**Comment by pesikj** [comment]
@motyc Opravil jsem překlep v názvu proměnné v JavaScriptu. V aplikaci vidím nyní jeden bod navíc, ale nevím, jetli je to ten chybějící centroid. Můžete to prosím zkontrolovat?

**Comment by motyc** [comment]
@pesikj Ano, vypadá to, že oprava pomohla.

**Comment by motyc** [comment]
### Test v0.3.5z77
Aktualizace stavu:

- [ ] _PAS - tooltip u bodu vymezujícího nález není vůbec. Řešit jako pro projekt._ - nyní se zobrazí jen prázdný label i tooltip; tipuji, že neproběhlo doplnění klíče do html template
- [ ] Knhovna 3D - popisek se zobrazí, ale vždy jde o klíč, nikoli o obsah z Rossetty:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/6212276d-9162-4f50-b93f-38d8c21603fe)
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/15343f71-0da6-4ddc-83ee-680e148a1bca)
- [ ] U importovaných PIAN (viz Uživatelský import geometrie PIAN #298) zbylo: _po kliknutí vyskakuje (logicky) prázdný tooltip, protože importovaný PIAN nemá a nemůže mít žádná napojení, neměl by se tak zbytečně otevírat (kliknutí nemusí dělat nic)_

**Comment by pesikj** [comment]
@motyc V aktuální verzi se zobrazuje ident pianu ze souboru

![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/15179154/1901897d-c9a4-424d-8df8-22466ae8043a)

**Comment by motyc** [comment]
@pesikj To je ok, problém je po kliknutí, kdy se zobrazí prázdný pop-up.

**Comment by motyc** [comment]
@pesikj Tady je trochu matoucí ta tabulka s příkladem, protože testovací data jsou nazvána jako existující PIAN. To v praxi nikdy nenastane, uživatelé to budou mít pojmenované svými popisky.

**Comment by motyc** [comment]
### Test v0.3.5z118
@jiri-bartos-huld Aktualizuji podle dohody. Chyby jsou spojené se zobrazením pop-up po kliknutí na PIAN.

- [ ] Pokud kliknu na centroid aktivního záznamu, vyskočí prázdný pop-up.
- [ ] Pokud kliknu na PIAN aktivního záznamu nebo libovolný jiný PIAN, na okamažik se zobrazí načítací kolečko, ale pop-up se nezobrazí.

V obou případech by se měl zobrazit pop-up se seznamem napojených DJ (se zohledněním oprávnění). Dříve to fungovalo, něco se jen muselo rozbít.

**Comment by jiri-bartos-huld** [comment]
1./opraveno
![obrazek](https://github.com/ARUP-CAS/aiscr-webamcr/assets/77389730/b4548dbf-a7c0-4962-9782-111753b628e9)
2./opraveno
![obrazek](https://github.com/ARUP-CAS/aiscr-webamcr/assets/77389730/e5ad7ff5-6cb7-41cd-bc2d-219a9575cc58)

**Comment by jiri-bartos-huld** [comment]
@pesikj @motyc  vse pripraveno na MR
