### ISSUE TITLE
Úprava původních klíčů pro překlady

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-webamcr#558]
Navazuje na #354 

- Část klíčů nemá standardní schéma, ale jako klíč se užívá rovnou překlad. Text je třeba posunout do pole s překladem a klíč nastavit standardně.
- Problém nyní je i to, že některé klíče jsou sdílené pro více obrazovek (např. `Poznámka`), přitom bychom potřebovali upravit jen některý text.
- Řada klíčů je definována včetně html značky (tvořící její vnější obal) - to není moc vhodné kvůli překladu, pokud nejde o explicitní záměr (např. html v emailech).
- Existují klíče s proměnnými, kde je třeba zadokumentovat, jak lze s takovými překlady pracovat (např. informace k oznámení projektu), případně je též upravit/rozdělit.
- Některé texty v administraci vůbec nejsou, např. http://192.168.254.30:8080/projekt/edit/C-201227576 - `Datum zahajeni`; asi i všechny texty, které jsou součástí mapy

od @jnihnat
> tam sme sa bavili, ze to neni jednoduche, v aplikaci je pres 700 klicu, co neznamena ze to je 700 miest kde dany kluc je..., Neexistuje ziadny jednoduchy sposob, ako tohle upravit, je potrebne prejst kluc po kluci a upravit to v kode. Zaroven potom, ale bude treba spravit preklady. Priklad:
> v aplikacii je teraz "Odeslat" - to je i klic a zobrazuje se to i aplikaci, lebo to nema preklad.
> nahradime to na "common.button.odeslat" to se zacne zobrazovat v prekladech i v aplikaci
> nekdo pak musi zadat preklad do aplikace.
> Treba se teda dohodnout, jak to udelat a kdo co udela. zmena v aplikaci je jasna, ale pak zadani noveho prekladu?

**Comment by jnihnat** [comment]
@motyc k tomu druhemu bodu, chapu to spravne, ze chceme mit co preklad to klic, napr:
#: adb/forms.py:40 arch_z/forms.py:122 arch_z/tables.py:28
#: arch_z/templates/arch_z/arch_z_detail.html:75 lokalita/tables.py:68
#: projekt/forms.py:241 projekt/forms.py:491 projekt/models.py:96
#: projekt/templates/projekt/detail.html:286
#: projekt/templates/projekt/detail.html:448
msgid "Uživatelské označení"

rozdelit na 10 klicu? Protoze v kodu je 10x

jinak uz mam script ktory najde preklad podle vyskytu v kodu, akurat se jeste musim dohodnout s @pesikj jak to presne udelat, protoze mi pri tom nemuze zasahovat do kodu aby se mi radky neposunuli.

**Comment by motyc** [comment]
@jnihnat Ano, protože jinak nebude v případě potřeby možné popis pole nijak upřesnit pro dané view. Sice tedy počet klíčů nabyde, ale protože máme název pole vždy i v názvu klíče, je snadné najít všechny najednou a překlad rozkopírovat. Bylo by tedy fajn být v tvorbě názvu klíče konzistentní (vč. buttonů atd.).

**Comment by jnihnat** [comment]
jo nazev klicu udelam podle umistneni v adresari, napr hore uvedene by bylo:
adb.forms.adbForm.label.uzivatelske_oznaceni
arch_z.tables.archzTable.label.uzivatelske_oznaceni
projekt.models.projekt.label.uzivatelske_oznaceni
teda adresar pres bodky, pak trida a pak label/text a nakonec samostatny nazev.

**Comment by motyc** [comment]
@jnihnat Dokončil jsem revizi textů a stav je následující:
- nyní je vše, co je již přeloženo (tj. klíč má k sobě nějaký překlad) zkontrolováno a opraveno tak, aby tam nebyly chyby či divné texty
- vše ostatní jsem z různých důvodů vyprázdnil, aby to nemátlo, nebo aby bylo po úpravě klíče jasné, že je třeba překlad doplnit
- nevím, co znamená těch 51 překladů označovaných jako "zastaralé" a kde je případně najdu:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/a6b9c236-005d-4a42-bc63-4f8dbd68d00d)
- pokud by nebyl problém, bylo by bezva aktivovat přepínač na anglickou verzi - v té totiž není nic vyplněno a snadno by tak šlo porovnávat klíče a české texty přímo v aplikaci...
- celkově se v tom celkem jde vyznat, byť úplně konzistentní to není, ale to asi nemá příliš smysl řešit; níže ale vypisuji vyložené chyby, na které jsem narazil (neřeším PAS, oznámení a projekty, kde tuším není hotovo)

**Chyby** (identifikováno při průběžném testování)
- [ ] chybí v Rosetta (přitom v kódu je):
-- `arch_z.models.ArcheologickyZaznam.checkPredArchivaci.dokument.text2`
-- `arch_z.models.ArcheologickyZaznam.checkPredArchivaci.dj.text2`
-- `dokument.filters.dokumentFilter.uzemniPrislusnost.C.option`
-- `dokument.filters.dokumentFilter.uzemniPrislusnost.M.option`
- [ ] divný klíč:
-- `dokument.templates.create.generovatNovePotvrzeni.*` -> dokument.templates.create.region.*
-- `dokument.views.create_model_3D.submitButton.text` -> `dokument.views.create_model_3D.formHeader.label`
-- `lokalita.templates.dj.djUpdate.adbForm.submitButton` -> `lokalita.templates.dj.djUpdate.submitButton`
-- `dokument.forms.coordinatesDokumentForm.*` -> `pas.forms.coordinates.*`
-- `dokument.views.create_model_3D.submitButton.text` -> `dokument.views.create_model_3D.formHeader.label`
- [ ] nutno rozdělit klíč `dokument.templates.create_model_3D.submitButton.text`, aby byl různý pro:
-- http://192.168.254.30:8080/dokument/model/edit/X-C-3D-000000014
-- http://192.168.254.30:8080/dokument/model/zapsat
- [ ] http://192.168.254.30:8080/historie/lokalita/C-N9000723 - úplně chybí text “Historie lokality” v záhlaví (srov. http://192.168.254.30:8080/historie/arch-z/X-C-9000000011A)
- [ ] V Akcích, Lokalitách a EZ chybí text záhlaví na stránkách Domů a Zapsat (správně např. u projektu)
- [ ] http://192.168.254.30:8080/pas/zapsat - u volby souřadnic je navíc fixní řetězec “Souř. S.”
- [ ] http://192.168.254.30:8080/dokument/model - v hlavičce navíc model3d.entity.tootlbar.Zapsat.label
- [ ] http://192.168.254.30:8080/dokument/ - v hlavičce navíc dokument.entity.tootlbar.Zapsat.label
- [ ] chyba závorek ('xxx') - zobrazují se v modalu pro vytvořit část dokumentu a upravit část dokumentu
- [ ] ve filtracích se u některých polí od-do zobrazuje `&nbsp;`:
- http://192.168.254.30:8080/dokument/vyber - Rok vzniku, Rok výzkumu (neident. akce), Velikost (soubor), Počet stran (soubor), Rok události (extra data), Důvěryhodnost (extra data)
- http://192.168.254.30:8080/dokument/model/vyber - Rok vzniku
- [ ] http://192.168.254.30:8080/projekt/vyber - v části akce jedno pole popsáno "[invalid name]"
- [ ] V drtivé většině případů jsou opomenuty klíče pro překlad názvů sloupců tabulek a položek v levém menu
- [ ] tlačítka "Přejít" a "Upravit" pod tabulkami velikostí nerespektují obsah (jinak tlačítko “Přejít” by šlo dát před pole místo labelu a bylo by to ve výsledku praktičtější)
- [ ] lokalita obsahuje některé překlady, které nejsou pro ni vůbec relevantní - zdá se mi, že jsou tam některé části kódu, jako třeba k ADB, které pro lokality vůbec nevznikají; podobně např. test, že lokalita má NZ před odesláním (sice se nepoužívá, ale klíče a tedy asi i kód zůstaly)

**Comment by pesikj** [comment]
@motyc @jnihnat 
Zde si prosím rozdělte, co by měl kdo opravit. Myslím, že třeba bod *divný (výrazně zavádějící) klíč:* zvládne opravit @motyc nebo někdo jiný z ústavu.

**Comment by motyc** [comment]
@pesikj To samozřejmě mohu, jen nevím, do čeho všeho můžu zasahovat, abych něco @jnihnat neměnil pod rukama. Také nevím, zda po změně klíče nemusím udělat ještě něco dalšího, abych nevytvořil nějaký zmatek v překladech.

**Comment by pesikj** [comment]
Určitě bude potřeba se synchronizovat. Pokud to není priorita, tak navrhuji, aby vám Honza vyčlenil úkoly, na kterých budete pracovat, a Honza se mezitím může věnovat práci na oprávnění. Poté může dokončit zbývající části.

**Comment by motyc** [comment]
Ono já teď budu také dva týdny víceméně pryč, takže něco na tom dělat mohu případně od září... Spíš tedy třeba může nechat bokem to, co mohu pak dodělat já.

**Comment by jnihnat** [comment]
Ja to skusim dat pristi tyden dokopy tak aby to bylo udelano v nejakem formatu a aby ste to mohli potom uz upravovat sam ty klice @motyc.

**Comment by jnihnat** [comment]
@motyc klice nahrane a mnelo by vsetko sedet. Nehovorim ze se nemuze vyskytnout mala chybka ale nic zavratniho. Pokud by ste nahodou objevil cely soubor co je spatne a pod. dejte vedet kouknu na to.
Jinak prve dve odrazky som taky uz zapracoval. Na zbytku budu delat a snazit se dokoncit co nejdriv.

**Comment by motyc** [comment]
@jnihnat Díky moc, vypadá to, že to funguje. Z první dobré jsem narazil jen na to, že chybí řada klíčů pro http://192.168.254.30:8080/upravit-uzivatele/ (některé jsou, některé však ne).

Každopádně podrobně bych to otestoval, až doladíte ty výše referované věci. Jinak překlady budu průběžně editovat, když na něco narazím. Pokud bych někdy měl do administrace nezasahovat, dejte vždy prosím vědět.

**Comment by jnihnat** [comment]
vetsina veci opravena v #1202
co jsem neopravil:
- preklady v tabulkach - to bych nechal na vas, je potreba doplnit do tables.py souborov. napriklad v arch_z v AkceTable je verbose_name=_("arch_z.tables.AkceTable.katastr.label"),
- to leve menu by mnelo snad byt ok tedka
- neodstranoval som casti kodu, to kdyz tak v samostatnom issue na vymazani nepotrebneho napr. s prekladmi to nesouvisi
- /upravit-uzivatele - je prelozeno vse co bylo pred tim. problem podobne jako s tables.py tu se bere preklad z uzivatel/models.pu User. taky treba predelat na verbose_name=_("...")

To dodelani prekladu bych teda klidne nechal na vas, kdyz natrafite na nejakou sekci muzete klidne udelat sam a pak pull request a skontroluji to. obecne models.py a tables.py maji verbose_name a forms.py a filters.py maji label.

EN prepinani jsem taky dodelal v #1202

**Comment by motyc** [comment]
@jnihnat Děkuji moc. Jakmile bude nasazeno, vrhnu se na to a doladím zbytek. Případně budu volat o radu.

**Comment by motyc** [comment]
### Výsledek testu (v0.3.5z14)

- [ ] Potřebné úpravy zaneseny do https://github.com/ARUP-CAS/aiscr-webamcr/pull/1288 - prosím o revizi a merge
- [ ] [Tato tabulka](https://docs.google.com/spreadsheets/d/1it_kr3HCN2vv54SUvn696XaP9tKCgcHnqUCBeg4CGYw/edit#gid=2033966180) obsahuje přehled URL a jejich stavu. K ní legenda:
-- `ok` = v pořádku
-- `upr` = problémy vyřešeny editací, po merge znovu prověřím a potvrdím
-- `chyba EN` = část nebo celá stránka se při přepnutí do EN nepřepne, přestože klíče v Rosetta existují - je třeba vyřešit, pak znovu otestuji
-- `nelze testovat` = na stránku se nyní nelze kvůli bugům dostat (většina bude kvůli chybám oprávnění)
-- `vyjasnit` = potřebuji pokyn, jak správně editovat
-- `x` = není relevantní z hlediska textů
- [ ] Nevím jak správně editovat klíče pro sloupce obsažené v “columns_to_hide” (týká se všech tabulek)
- [ ] Všude chybí klíče pro ovládací prvky mapy - jak správně doplnit?
- [ ] https://github.com/ARUP-CAS/aiscr-webamcr/blob/dev/webclient/static/js/dz.js#L11 Nahrávání souborů - “Přiložte dokumentaci” + “Přiložte aktualizovaný soubor” + Zrušit nahrávání" + "Naozaj chcete zrušit nahrávání?" + "Odstranit soubor" - jak správně doplnit?
- [ ] Prosím o vysvětlení, co jsou ta "Zastaralá" hesla v Rosetta.

**Comment by jnihnat** [comment]
@motyc opravy v #1316 : 
- casti/cele stranky by uz mnely fungovat
- columns_to_hide - pokud mluvime o nazvech tech sloupcu tak to je to same jak u ostatnich sloupcu, teda to verboce_name co jse nastavoval
- mapa - doplneno map_translations do obou js souboru (arch_z_detail_mapa.js a mapa_projekty.js) a do html (archz - detail_common.html a projekty create, detail, edit) pridavani uz jednotlivych klicu do vsech souboru bych nechal na vas, prosim dodrzeni zapisu.
- dz - to same co mapa s promennou dz_trans a js soubory (dz.js a dz_import_pian.js) a html upload_file.html, index2.html, projekt.create.html a importovat_pian_modal.html
- zastarale - jsou to stare preklady, promazal bych to az budeme mit vsechno prelozeno.
- klidne muzete zitra zavolat kdyz si nebudete necim jist.

**Comment by motyc** [comment]
### Test v0.3.5z21
- [ ] Opět připraven pull na review a merge: https://github.com/ARUP-CAS/aiscr-webamcr/pull/1319
- [ ] Většina problémů s EN zmizela, ale stále zbyly stránky, kde se nepřehazuje do EN vše. Obvykle jsou to nadpisy modalů + některá tlačítka a hlavně pak stránky s tabulkami pro výběr záznamů. Vše opět viz https://docs.google.com/spreadsheets/d/1it_kr3HCN2vv54SUvn696XaP9tKCgcHnqUCBeg4CGYw/edit#gid=2033966180
- [ ] http://192.168.254.30:8080/arch-z/akce/detail/C-9723779A/dj/C-9723779A-D01 - nefunguje překlad pole typ (`dj.forms.createDjForm.typ.label`); problém bude asi v tom, že je k němu speciální definice, ale v tomto případě nevím, kam přesně label zapsat: https://github.com/ARUP-CAS/aiscr-webamcr/blob/303e72d2726e92ba0d7f13a80df89a6436fdfa63/webclient/dj/forms.py#L33

**Comment by motyc** [comment]
@pesikj @jnihnat Zdá se, že ty úpravy klíčů pro mapy nějak rozbily mapové okno - nejsou v něm vidět žádná tlačítka (v0.3.5z22), související klíče však v Rosettě jsou načteny dobře. Posupoval jsem podle vzoru, ale mohl jsem udělat chybu. Prosím o revizi, co se stalo. Do stejných souborů jinak bude jinak zasahovat i PR od @jiri-bartos-huld (#1322), tak by to bylo dobré zohlednit.

**Comment by motyc** [comment]
### Test v0.3.5z23
- [ ] Při posledním zpracování jsem opomenul editovat dva soubory: [mapa_akce.js](https://github.com/ARUP-CAS/aiscr-webamcr/blob/dev/webclient/static/js/mapa_akce.js) a [mapa_oznameni.js](https://github.com/ARUP-CAS/aiscr-webamcr/blob/dev/webclient/static/js/mapa_oznameni.js). Další připraven pull na review a merge: #1325 (obsahuje i další drobné korekce)
- [ ] Většina problémů s EN zmizela, ale stále zbyly stránky, kde se nepřehazuje do EN vše. Obvykle jsou to nadpisy modalů + některá tlačítka a hlavně pak stránky s tabulkami pro výběr záznamů. Vše opět viz https://docs.google.com/spreadsheets/d/1it_kr3HCN2vv54SUvn696XaP9tKCgcHnqUCBeg4CGYw/edit#gid=2033966180
- [ ] http://192.168.254.30:8080/arch-z/akce/detail/C-9723779A/dj/C-9723779A-D01 - nefunguje překlad pole typ (`dj.forms.createDjForm.typ.label`); problém bude asi v tom, že je k němu speciální definice, ale v tomto případě nevím, kam přesně label zapsat: https://github.com/ARUP-CAS/aiscr-webamcr/blob/303e72d2726e92ba0d7f13a80df89a6436fdfa63/webclient/dj/forms.py#L33
- [ ] Prosím ověřit, že je v pořádku tento kód a zda bude fungovat i po změnách v #1319, protože je to zjevně fixováno na nějaký konkrétní řetězec: https://github.com/ARUP-CAS/aiscr-webamcr/blob/7d8d0330357832585bbada95804d84ecb833db68/webclient/static/js/arch_z_detail_map.js#L936
- [ ] https://github.com/ARUP-CAS/aiscr-webamcr/blob/fe75aa80e32973f1ab53a5875fd145b5b2f1def4/webclient/lokalita/templates/lokalita/create.html#L31 - tlačítko rozdělit zvlášť pro `arch-z/lokalita/zapsat` a `arch-z/lokalita/edit/` 
- [ ] http://192.168.254.30:8080/dokument/model/* - v mapě chybí tlačítka (možná opraví #1325, ale nevím)
- [ ] http://192.168.254.30:8080/projekt/edit/C-202300514 - mapa se nezobrazí vůbec (možná nesouvisí s tímto issue a vyřeší opravy mapy od @jiri-bartos-huld)

**Comment by jnihnat** [comment]
opravy v #1367 
udelal som i preklad na heslare, pokud je EN bere se preklad ze sloupce heslo_en
pro notifikace jsem udelal obdobne na text_cs a text_en

**Comment by motyc** [comment]
### Test v0.3.5z47
https://docs.google.com/spreadsheets/d/1it_kr3HCN2vv54SUvn696XaP9tKCgcHnqUCBeg4CGYw/edit#gid=2033966180 - tabulka aktualizována, konkrétní typy chyb vypisuji níže.
- [ ] _Stále stejná chyba:_ http://192.168.254.30:8080/arch-z/akce/detail/C-9723779A/dj/C-9723779A-D01 - nefunguje překlad pole typ (`dj.forms.createDjForm.typ.label`); problém bude asi v tom, že je k němu speciální definice, ale v tomto případě nevím, kam přesně label zapsat: https://github.com/ARUP-CAS/aiscr-webamcr/blob/303e72d2726e92ba0d7f13a80df89a6436fdfa63/webclient/dj/forms.py#L33
- [ ] _Zde nevím, zda prověřeno - prosím o případné vysvětlení:_ Prosím ověřit, že je v pořádku tento kód a zda bude fungovat i po změnách v #1319, protože je to zjevně fixováno na nějaký konkrétní řetězec: https://github.com/ARUP-CAS/aiscr-webamcr/blob/4674bf29e8bd0561e33e9cabe80708b274da1bf0/webclient/static/js/arch_z_detail_map.js#L994
- [ ] http://192.168.254.30:8080/uzivatel/edit/ - chybí překlady pro checkboxy notifikací. Myslel jsem, že se používá `uzivatel.templates.notifikace.*`, ale není to tak. _Nyní se nezobrazuje žádný text, jen checkboxy._
- [ ] V kontextu https://github.com/ARUP-CAS/aiscr-webamcr/issues/1327#issuecomment-1808938811 vyřešit překlad pro: https://github.com/ARUP-CAS/aiscr-webamcr/blob/5231fed1e368d1a2a634c7aac37955c69705c44e/webclient/static/js/arch_z_detail_map.js#L467
- [ ] u modalů se nyní vyskytuje několik variant chyb:
-- chyba EN (titulek + button) - 1 poslední případ
-- error 500 - asi nějaká bota v kódu - 6 případů
-- fixně se vypisuje "title" a "button" - 6 případů
- [ ] http://192.168.254.30:8080/pas/spoluprace/vyber?sort=organizace_vedouci&sort=spolupracovnik - neotestují kvůli `'UzivatelSpolupraceListView' object has no attribute 'hasOnlyVybrat_header'`
- [ ] všechny formuláře pro filtraci mají problém s překladem nadpisů polí + s překladem nadpisů oddělovačů (rozbalovací části formuláře)
- [ ] v detailu a editaci dokumentu je problém s překladem polí Let a Dokumentové osoby; sám jsme zkoušel opravit již posledně, ale zjevně to nezabralo.

**Comment by jnihnat** [comment]
tedka jsem si vsiml ze u prveho resime dj.forms.createDjForm.typ.label a ne to co je v dropdowne :D Kouknu na to...

if (e.name == "AMČR Piany") {  - tohle by malo fungovat opravoval som a overoval u sebe

preklady notifikaci, hodil jsem do DB k modelu nove sloupce text_cs a text_en. Nevsiml jsem si ze to nemame v adminu. Pridam pod Heslare at se to da jednoducho upravovat? Udelam opravu at se vraci ident pokud neni zadny preklad?

 L.marker([corX, corY], { icon: pinIconRedPoint }).bindTooltip('Navržený pian').addTo(drawnItems); //'Navržený pian'  - taky opraveno a malo by fungovat

Na zvysok sa skusim pozriet este dnes/zajtra

**Comment by motyc** [comment]
@jnihnat Díky za rychlou reakci. Ještě jsem doplnil čtyři body, co jsem si poznamenal vedle a zapomněl připsat.

- ad notifikace - ok, to by šlo; já jsem po pravdě z toho předchozího komentáře nepochopil, co tím vlastně myslíte
- ad `e.name == "AMČR Piany"` - a co tohle vlastně je? je mi to celé nějaké podezřelé, proč se ptáme na takto specifický řetězec a ne nějakou proměnou/konstantu...
- ad `Navržený pian` - úplně nerozumím, jak to může fungovat, když to [zde](https://github.com/ARUP-CAS/aiscr-webamcr/blob/dev/webclient/static/js/arch_z_detail_map.js) stále vidím stejné, jako před tím - vždyť tam žádný překlad není?

**Comment by jnihnat** [comment]
k e.name - to je dotaz na @jiri-bartos-huld protoze to jsou mapy a tam do toho moc nevidim

Navrzeny pian - v kodu uz je map_translations['TempPIAN'], problem delaly ty [] v kterych ten retezec byl, nekde to treba je a nekde ne...

**Comment by jnihnat** [comment]
snad finalni opravy v #1372

**Comment by motyc** [comment]
### Test v0.3.5z49
Tak úplně poslední kolo to bohužel nebylo, ale tentokrát už myslím bude. Co zbývá:
- [ ] `dj/zmenit-katastr/<str:ident_cely>` - nejde testovat; DJ s přesností na katastr nyní nejdou otevřít (např. http://192.168.254.30:8080/arch-z/akce/detail/C-9000094A/dj/C-9000094A-D01) - vrací `Unsupported lookup 'neq' for AutoField or join on the field not permitted.`
- [ ] překlady heslářů nefungují pro vícestupňové hesláře - _nadále platné_
- [ ] `filter_by_oblast` (https://github.com/search?q=repo%3AARUP-CAS%2Faiscr-webamcr%20filter_by_oblast&type=code) - související heslář nevím jak z hlediska klíčů nastavit
- [ ] http://192.168.254.30:8080/uzivatel/edit/ - `Hlavni role` - i přes snahu nevím, jak opravit
- [ ] http://192.168.254.30:8080/pas/vyber - zde zůstal neošetřený problém s filtračním formulářem

Zbylé už je snad ok (jakmile nasadíme mé drobné opravy výše).

**Comment by motyc** [comment]
@jnihnat mrkněte do filtračních formulářů, to nešlo nikde

**Comment by motyc** [comment]
### Test v0.3.5z61
Tak poslední drobnost:
- [ ] `filter_by_oblast` - již je v Rosttě, ale nefunguje přepnutí na EN

**Comment by jnihnat** [comment]
@motyc ted jsem skousel a zobrazuje se spravne jak pro projekt tak pro pas:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/57906106/92196e1a-bbe0-42f1-9b58-07dd47d42c53)

![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/57906106/704e4497-667a-4f31-b822-8aa6446f377d)

**Comment by motyc** [comment]
@jnihnat Jde o obsah toho hesláře, ne nadpis :)

**Comment by jnihnat** [comment]
opraveno v #1409 - upravil som nacitani nahledu obrazu v PAS. tedka to neblokuje nacitani javascriptu. Nezobrazili se autocomplete seznamy pokud se nanecetli vsechny obrazky. Jedina nevyhoda je, ze se donacitavaji az pri skrolovani, na druhu stranu nezatazujeme server zbytocnym nacitanim pokud je ani nezobrazime. Dejte vedet ci to nechat a pripadne ci to dodelat na dalsi seznamy, je to jednoducha vec na minutu.

**Comment by motyc** [comment]
@jnihnat Bezva, na to jsem narazil a určitě bude lepší, když to na sebe čekat nebude. Ono náhledy asi budeme do budoucna nějak cachovat (viz #1090), ale určitě to bude lepší upravit všude.

**Comment by jnihnat** [comment]
@motyc - tohle je asi na vas na testovani, nebo je tu jeste nejaka chyba co jsem prehledl? Dekuji

**Comment by pesikj** [comment]
Přehodil jsem to k testování.

**Comment by motyc** [comment]
@jnihnat @pesikj Bohužel to zůstává stále stejné:
![image](https://github.com/ARUP-CAS/aiscr-webamcr/assets/20186892/f338b52e-e64c-4004-b1c9-8d30e6bbcd78)

**Comment by jnihnat** [comment]
mala chybka, pridam k opravam opravneni na kterych tedka delam
