### ISSUE TITLE
Revize stavu struktury DB - dokončení

### ISSUE THREAD

**Issue by pbartosova** [ARUP-CAS/aiscr-webamcr#818]
**Je v https://github.com/ARUP-CAS/aiscr-webamcr/blob/dev/migrace/44_migrace_revize_db.sql, ale zatím neaplikováno v DB:**
- [ ] ruian_katastr.nazev – doplnit unique constraint (nepůjde před #372)
- [ ] ruian_katastr.kod – doplnit unique constraint (nepůjde před #372)
- [ ] ruin_kraj.definicni_bod – chybí not null (**nepůjde nastavit - chybí data - musí řešit ARÚ**)
- [ ] ruin_kraj.hranice – chybí not null (**nepůjde nastavit - chybí data - musí řešit ARÚ**); bylo chybně - oprava v https://github.com/ARUP-CAS/aiscr-webamcr/commit/fd298d3ae55c98439a07938bf893d9390d83dcb0
- [ ] ruian_okres.definicni_bod – chybí not null (**nepůjde nastavit - chybí data - musí řešit ARÚ**) (nepůjde před #372)
- [ ] ruian_okres.hranice – chybí not null (**nepůjde nastavit - chybí data - musí řešit ARÚ**) (nepůjde před #372)

_Originally posted by @pbartosova in https://github.com/ARUP-CAS/aiscr-webamcr/issues/474#issuecomment-1354490559_
